### ISSUE TITLE
Inconsistent Data

### ISSUE THREAD

**Issue by jnfrati** [cms-dev/cms#1020]
Hello, I'm kind of newbie in all of this things so I'm sorry if its an stupid question. 
When cms is trying to communicate with the Ranking Web Server I get this exception

>     Exception cmsranking.Entity.InvalidData:
>     
>         [entity 216] Inconsistent data
>     
>     Traceback (most recent call last):
>     File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmsranking/RankingWebServer.py", line 208, in put_list
>         self.store.merge_list(data)
>       File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmsranking/Store.py", line 240, in merge_list
>         raise exc

I have the cms.ranking.conf as the readthedocs indicates and the cms.conf ranking line is ok.
I'm running cms v1.2 on ubuntu 14.04 with postgresql 9.3.

**Comment by stefano-maggiolo** [comment]
Hello Nicolas,

RWS stores its own copy of the score data, and that exception usually means something went wrong with the copy (either some data was deleted or got corrupted in some way). The easiest way to fix is to stop `cmsRankingWebServer` and `cmsProxyService`, run `cmsRankingWebServer -d` to clear the copy of the score data, then launch again `cmsRankingWebServer` and `cmsProxyService` to resent all the data.

PS: you should update to v1.3, v1.2 is not supported anymore, including for security updates.

**Comment by jnfrati** [comment]
Thank you a lot! It worked. I had to start first cmsRankingWebServer and after the cmsProxyService. Sorry for bothering!

**Comment by stefano-maggiolo** [comment]
No worries at all, if you have any question feel free to join the gitter chat ( https://gitter.im/cms-dev/cms )
