### ISSUE TITLE
The new score indicator (for use with max_subtask score mode) shows 0/100 when submissions are sent before the start of the contest with unrestricted users

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#1054]
See title

**Comment by edomora97** [comment]
And it's zero also in the ranking page on AWS (maybe intended?)

**Comment by stefano-maggiolo** [comment]
I haven't looked into it yet, but are you sure the submission is official?

**Comment by edomora97** [comment]
Oh, actually it's not official, I didn't think about that. Marking the solution as official solves both the problems.

The only "strange" thing is scoring points but seeing that red banner anyway. I think that in this situation (testing with unrestricted used) that banner should be changed, maybe removed, or maybe just add a message like "not including unofficial submissions" or something like that.

**Comment by stefano-maggiolo** [comment]
More importantly, it would be very confusing if it happens in an actual analysis session for real contestants. I think we should make it very clear in the submissions list in CWS when a submission is official and when it's not (possibly, having two separate lists).

**Comment by wil93** [comment]
The most "intuitive" solution would probably be to show "no submissions" as the score when there are no official submissions (in this way, contest admin will not be surprised by this behavior, like we were)

As for the analysis part, either a separate list or different score colors (e.g. red to green for official submissions, and white only for unofficial submissions) could work

**Comment by wil93** [comment]
This was addressed in #1091
