### ISSUE TITLE
a small change to improve the managing of the order of tasks within a contest

### ISSUE THREAD

**Issue by romeorizzi** [cms-dev/cms#1060]
The situation right now is:
the contest manager selects one task in the list by means of the radio button on his left,  and then selects an action among: "delete", "move up" and "move down".
Adding the two buttons "move top" and "move bottom" should be easy , and would already make a big difference when one manages contests with long lists of tasks.
A more refined solution could be to add a field contained a number (preimposted to 1) to the immediate right of both the button  "move up" and the button "move down".
In this way one could make big jumps in one single stroke (form O(n^2) moving steps downto O(n)), and also the interface would be immidiatley clear of what action the "move up" and "move down". buttond actually trigger.

**Comment by stefano-maggiolo** [comment]
I agree, that interface is both ugly and awkward to use. Just to get an idea, how many tasks are you talking about? 10, 100, 1000... ?

The problem will disappear with the (very) long term plan of rewriting AWS's UI, but I think you're suggestions would be a quick way to make it easier to use. Would you be comfortable sending a patch, possibly with some pointers?
