### ISSUE TITLE
teaching-assistants should have access to the admin ranking features

### ISSUE THREAD

**Issue by romeorizzi** [cms-dev/cms#1061]
RIght now cms offers two ranking facilitie, one for admins and one for contentans.
When teaching massive courses it would be helpful that the tutors (which are not necessarily admins since they may not have the comptences and the full trust) can also have access to the admin ranking service since it is very helpful in order to detect students in difficulty.
At the same time, the cms already supports a few categories of users, like e.g. hidden or moderator.
I would suggest to extend the accessibility of the Ranking functionality (and the possibility of downloadin the ranking.csv file therein contained) to one of the above categories.
Even better would be to introduce a further category. A suitable name for it could be "teaching-assistant". 
The teaching-assistant should have access to the admin ranking features.

**Comment by stefano-maggiolo** [comment]
We have admins with different permission, I believe one is "read only", that essentially would allow to see all of the information in AWS without changing anything. Does this solve your feature request?

**Comment by romeorizzi** [comment]
ok, thanks Stefano. With William we now found an admin type of suitable power.
