### ISSUE TITLE
Various styling errors with CWS

### ISSUE THREAD

**Issue by kuroni** [cms-dev/cms#1077]
**Description:**

1. When a submission receives 100/100 for a task with non-100 total but with decimal precision (eg. the total score is not 100 but 99.9999), the general scoring uses `score_0_100` format instead of `score_100`.

2. When a submission receives "Compilation failed" verdict, the loading GIF in the general scoring remains.

[Demo screenshots](https://imgur.com/a/jOGB2bq)

**CMS version:** v1.4.rc1
**Was CMS installed:** yes
**Using a virtualenv:** yes

**Comment by stefano-maggiolo** [comment]
Also backported to v1.4. Thanks!
