### ISSUE TITLE
SQLAlchemy Issue 

### ISSUE THREAD

**Issue by ammcom255** [cms-dev/cms#1119]
**Description:** 
I have used CMS 1.3 for two years on my machine running Ubuntu 16.04 serving about 50 contestants, I decided to use CMS 1.4 on the same machine, so I Installed a fresh Ubuntu 18.04 and installed CMS 1.4, But with same usual contest environment and serving 26 contestants, CMS fails to open on most client machines with the following log:
QueuePool limit of size 5 overflow 10 reached, connection timed out
The error occurs when more than FIVE CLIENTS connect simultaneously. 
To confirm it is a software problem I use a backup server that runs 16.04 and cms 1.3, WITH SAME INFRASTRUCTURE including network and contestant machines and it runs perfectly.
I suspect the version of SQLAlchemy was the problem which was 1.11 where the current version is 1.21, the problem is the default pool size of SQLAlchemy which is 5.
**Steps to reproduce:**
1. Install Ubuntu 18.04
2. Install Python dependency using apt-get which install version 1.11 of SQLAlchemy
3. Run CMS with 10 clients 

**Expected:** It should run

**Actual:** Contest web server stops serving clients if there is more than 5 clients.

### System Information

**CMS version:** 1.4 RC0
**Was CMS installed:** yes
**Using a virtualenv:** no
"OS" Ubuntu 18.04
SQLAlchemy version 1.11 installed by apt-get

**Comment by andreyv** [comment]
How long is the response if you connect with just one client?

You can join [Gitter chat](https://gitter.im/cms-dev/cms) to discuss the issue.

**Comment by ammcom255** [comment]
For one client it works perfectly, the problem starts when more than 5 clients connect

**Comment by andreyv** [comment]
Did you investigate this further? Is it still reproducible, also with CMS master?

Here's a couple of questions:
- Are you running a reverse proxy? What is its configuration? Did you set a big `keepalive` value in Nginx `upstream` module? Does the same happen without the proxy?
- Post ContestWebServer logs
- Do you observe abnormal CPU usage or other things on the server?
- How much time does it take to serve one CWS request?

**Comment by andreyv** [comment]
No response; CMS has since been updated to run on Ubuntu 20.04 and with newer SQLAlchemy. Closing. Feel free to reopen if you still experience the problem with CMS master.
