### ISSUE TITLE
Ranking webserver: WRN Wrong JSON

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#1136]
## Issue template

**Description:** Ranking webserver produces warningn `WRN  Wrong JSON` and nothing is visualized in the ranking page.

**Steps to reproduce:**
1. Add some submissions.

**Expected:** Submissions are visualized in the ranking page.

**Actual:** Ranking page is empty

### Logs

```
2019-09-29 23:27:47.434  WRN  Wrong JSON.
    http://127.0.0.1:8890/contests/

127.0.0.1 - - [2019-09-29 23:27:47] "PUT /contests/ HTTP/1.1" 400 303 0.009443
2019-09-29 23:28:47.469  WRN  Wrong JSON.
    http://127.0.0.1:8890/submissions/

127.0.0.1 - - [2019-09-29 23:28:47] "PUT /submissions/ HTTP/1.1" 400 303 0.005966
```

### System Information

**CMS version:** `v1.4.rc1`
**Was CMS installed:** yes
**Using a virtualenv:** no
**Postgres version:** 9.5
**Distribution and version:** Ubuntu 16.04 LTS

**Comment by ray1422** [comment]
I have the same problem.

**Comment by stefano-maggiolo** [comment]
We had some trouble with JSON with the transition between python 2 and 3, this might be the underlying cause - can you also make sure you start with a clean data directory for RWS?

Can you give me access to the JSON files stored in the data directory after a submission is sent? Minimal example welcome :)

**Comment by ray1422** [comment]
What should I do after I edit the code? I modified it trying to print the value of "request.stream", but seems not work.
Should I build it again?

**Comment by ray1422** [comment]
I add the following on about line 216
```python
print(request.stream.readlines())
```
and it printed `[]`

**Comment by stefano-maggiolo** [comment]
Line 216? We might have a mismatch in the version of that file. Anyway, make sure you do that before trying to parse the JSON, otherwise the stream is already read.

**Comment by ray1422** [comment]
```
2019-09-30 13:39:42.693  INF  Using config file /usr/local/etc/cms.ranking.conf.

[b'{"chisc_5fwater_5fcontest": {"score_precision": 0, "begin": 1569819600, "end": 1569834000, "name": "\\u4e2d\\u548c\\u8cc7\\u7814 \\u6c34\\u984c\\u5927\\u8cfd"}}']
2019-09-30 13:39:57.319  WRN  Wrong JSON.
    http://localhost:8890/contests/
```

**Comment by ray1422** [comment]
`cmsranking/RankingWebServer.py`
```
try:
    print(request.stream.readlines())                                                                                                                 
    data = json.load(request.stream)
```

**Comment by stefano-maggiolo** [comment]
Yep, that change is fine. Also the JSON seems to load fine both on 2.7 and 3.6. What version of Python are you using? I remember having trouble with JSON and 3.5, IIRC due to this: 

> json.load() and json.loads() now support binary input. Encoded JSON should be represented using either UTF-8, UTF-16, or UTF-32. (Contributed by Serhiy Storchaka in bpo-17909.)

**Comment by stefano-maggiolo** [comment]
@CristianCantoro is that true for you as well? If so, please close the bug.

**Comment by wil93** [comment]
@stefano-maggiolo would it be a good idea to add a version check somewhere (e.g. in conf.py) so that any CMS command will complain if run with an unsupported Python version?

**Comment by ray1422** [comment]
If someone have the same problem, just replace `data = json.load(request.stream)` with `data = json.loads(request.stream.readlines()[0].decode())`, then it works fine.

**Comment by CristianCantoro** [comment]
@ray1422 wrote:
> oops, I'm using python 3.5 .
> sorry for that I don't noticed the version of python I'm using because it's the default version of ubuntu 16.04

Good catch, I am in the same situation. I am using Ubuntu 16.04 and I have migrated from CMS `v1.3.2` which was using Python 2.7.12 to CMS `v1.4.rc1` which uses Python 3 and the default for Python3 is `v3.5.2`.

Here's the fix for posterity:


### Step 1: get Python 3.6 (optional)

If you need to install a newer version of Python you may use deadsnake's PPA:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
```
(more info about [ppa:deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa))


### Step 2: set Python 3 alternatives

List the version of Python 3 you have available on your machine:
```
$ ls -lh /usr/bin/python3.?
-rwxr-xr-x 2 root root 4,3M ago 20 22:08 /usr/bin/python3.5
-rwxr-xr-x 2 root root 4,6M lug  4 02:52 /usr/bin/python3.6
```

We now set the system version of Python using `update-alternatives`:
* we will keep  the default Python for the `python` command, i. e. `/usr/bin/python`, to be Python 2.7; this is good because in Ubuntu 16.04 many programs expect this.
* we will set as default Python for Python 3, that is the `python3`, i. e. i. e. `/usr/bin/python`, to be Python 3.6
* in any case, we will assign priorities to each Python version so that in auto mode the version of Python 3 to be used is Python 3.5 and then we will override this choice.

Set Python 3.5 as highest priority alternative for `python3`:
```
$ sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 10
update-alternatives: using /usr/bin/python3.5 to provide /usr/bin/python3 (python3) in auto mode
```

Then set Python 3.6 as another alternative for `python3`:

```
$ sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
```

Now we manually change the default Python 3 version to `python3.6`:
```
$ sudo -EH update-alternatives --config python3
There are 2 choices for the alternative python3 (providing /usr/bin/python3).

  Selection    Path                Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python3.5   10        auto mode
  1            /usr/bin/python3.5   10        manual mode
  2            /usr/bin/python3.6   1         manual mode

Press <enter> to keep the current choice[*], or type selection number: 2
update-alternatives: using /usr/bin/python3.6 to provide /usr/bin/python3 (python3) in manual mode
```


And we can confirm that by default `python3` is actually `python3.6` with the following:
```
$ python3 --version
Python 3.6.9
```

### Step 3: get pip3 / fix pip3 installation (optional)

If you need `pip3` or if launching `pip3` gives you this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line7, in <module>
      from pip._internal import main
ImportError: No module named _internal
```

you can reinstall `pip3` ([https://pip.pypa.io/en/stable/installing/](instructions source)):
```
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py
```

Then you can reinstall CMS as usual and everything works.

**Comment by andreyv** [comment]
There's also this: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires. Although Ubuntu 16.04 doesn't have new enough pip/setuptools versions for this to have effect.
