### ISSUE TITLE
User testing does not pick up header files

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#1153]
User testing does not pick up header files from the task, resulting in failing compilation. User submission functions normally (submitting only the source code).

**Steps to reproduce:**
1. Create a task with a grader and a header file
2. Go to user testing, upload the source code and the grader code, and an input file.

**Expected:** the test code is compiled with the grader and executed

**Actual:** Compilation files
```
grader.cpp:11:17: fatal error: taskname.h: No such file or directory
compilation terminated.
taskname.cpp:2:17: fatal error: taskname.h: No such file or directory
 #include "taskname.h"
                 ^
compilation terminated.
```

### Logs

N/A

### System Information

**CMS version:** 1.4rc1
**Was CMS installed:** yes
**Using a virtualenv:** no
**Postgres version:** 9.5
**Distribution and version:** Ubuntu 16.04.6 LTS

**Comment by CristianCantoro** [comment]
One thing that I have realized is that in previous versions of CMS when testing tasks with a grader, it only asked for the source code and not for the grader source code.

## Old user testing interface
![CMS 1.3 user testing interface](https://i.imgur.com/a3OMUgH.png)

## Current (`cms1.4rc1`) user testing interface
![CMS 1.4rc1 user testing interface](https://i.imgur.com/wUFyNb1.png)

I am not really sure why his change was made since the grader is not something that contestants can change. We do provide the code of the grader for local testing, but in principle, this should not be necessary.

**Comment by CristianCantoro** [comment]
It looks like that the breaking commit is https://github.com/cms-dev/cms/commit/a64cc71b84c0e18195b454db8a65d23befd0e9be, but I do not know if it is safe to revert this change, What do you think @stefano-maggiolo?

**Comment by andreyv** [comment]
@CristianCantoro This is actually the expected behavior. See https://cms.readthedocs.io/en/latest/Task%20types.html#batch:
> Batch supports user tests; if a grader is used, the contestants must provide their own grader (a common practice is to provide a simple grader to contestants, that can be used for local testing and for server-side user tests).

As you noted, admins need to provide a grader to contestants for local testing, and so it can be submitted together with the solution.

**Comment by andreyv** [comment]
The issue with headers should be fixed now.

**Comment by CristianCantoro** [comment]
@andreyv said:
> The issue with headers should be fixed now.

thanks, @andreyv, will this fix be in the next release?

**Comment by andreyv** [comment]
@CristianCantoro Sure, but for now you can also take c279f8103350beff91970854899414bb977b4925 and apply it manually.

**Comment by CristianCantoro** [comment]
@andreyv said:
> @CristianCantoro Sure, but for now you can also take [c279f81](https://github.com/cms-dev/cms/commit/c279f8103350beff91970854899414bb977b4925) and apply it manually.

I also confirm that this patch works successfully.
