### ISSUE TITLE
setup.py install fails with ImportError: No module named future.builtins.disabled

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#1166]
**Description:** setup.py install fails with `ImportError: No module named future.builtins.disabled`

```bash
$ ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 37, in <module>
    from future.builtins.disabled import *  # noqa
ImportError: No module named future.builtins.disabled
```

**Steps to reproduce:**
1. Install CMS prerequisites as per the [Installation](https://cms.readthedocs.io/en/v1.4/Installation.html) docs
2. Run `./setup.py install`

**Expected:** the installation completes without error.

**Actual:** the error described above is encountered.

### Logs

N/A

### System Information

**CMS version:** 1.4.rc1
**Was CMS installed:** trying to install
**Using a virtualenv:** no
**Postgres version:** not relevant
**Distribution and version:** Ubuntu 18.04 LTS

**Comment by CristianCantoro** [comment]
To solve the problem on Ubuntu 18.04 it is sufficient to install the package `python-future`:
```
sudo apt-get install python-future
```

Note that at the beginning of the script you have:
```
/usr/bin/env python
```
(i. e. python2)

while the documentation says to use `python3`: `python3 setup.py`.

**Comment by andreyv** [comment]
Thanks for the report and the workaround.

As you observed, `python3 setup.py` should resolve the issue.

The files in v1.4 have the `/usr/bin/env python` shebang because this version supports both Python 2 and Python 3. The version is selected at installation time by running `setup.py` under the corresponding interpreter, either `python` or `python3`. The former is the default when you just run `./setup.py`.

The next CMS version will drop support for Python 2.

**Comment by CristianCantoro** [comment]
@andreyv wrote:
> The files in v1.4 have the `/usr/bin/env python` shebang because this version supports both Python 2 and Python 3. The version is selected at installation time by running `setup.py` under the corresponding interpreter, either `python` or `python3`. The former is the default when you just run `./setup.py`.

Thanks for this clarification, it wasn't clear to me that this was the behavior of the `/usr/bin/env python` shebang.

However, when running `python3: python3 setup.py` I get a different error for which I will open a different bug report.

**Comment by CristianCantoro** [comment]
Maybe I should live this issue open because it also affects `python3`.

**Comment by CristianCantoro** [comment]
This error was as well due to the fact that I didn't run the command:
```
pip3 install -r requirements.txt
```

If you run it, everything works.
