### ISSUE TITLE
setup.py install fails with error: invalid command 'compile_catalog'

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#1168]
**Description:** setup.py install fails with `error: invalid command 'compile_catalog'`

**Steps to reproduce:**
1. Install CMS prerequisites as per the [Installation](https://cms.readthedocs.io/en/v1.4/Installation.html) docs
2. Run `python3 setup.py install`

**Expected:** the installation should have completed without error.

**Actual:**  the error described above is encountered.

```
$ sudo python3 setup.py install
/usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.4.rc1' to '1.4rc1'
  normalized_version,
running install
running bdist_egg
running egg_info
writing cms.egg-info/PKG-INFO
writing dependency_links to cms.egg-info/dependency_links.txt
writing entry points to cms.egg-info/entry_points.txt
writing top-level names to cms.egg-info/top_level.txt
reading manifest file 'cms.egg-info/SOURCES.txt'
writing manifest file 'cms.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running compile_catalog
error: invalid command 'compile_catalog'
```

### Logs

N/A

### System Information

**CMS version:** 1.4.rc1
**Was CMS installed:** trying to install
**Using a virtualenv:** no
**Postgres version:** not relevant
**Distribution and version:** Ubuntu 18.04 LTS

Note that this error is encountered after solving https://github.com/cms-dev/cms/issues/1166, i. e. installing `python3-future`.

**Comment by wil93** [comment]
If I recall correctly, the 'compile_catalog' error happens when python-babel is not installed.

It shouldn't happen if all dependencies are installed before running the install command:

```
pip3 install -r requirements.txt
```

**Comment by CristianCantoro** [comment]
@wil93 wrote:
> If I recall correctly, the 'compile_catalog' error happens when python-babel is not installed.
> 
> It shouldn't happen if all dependencies are installed before running the install command:
> 
> ```
> pip3 install -r requirements.txt
> ```

You are aboslutely right, I didn't run the installation of `requirements.txt`. My mistake, I'm sorry.

**Comment by nizami01** [comment]
gijdllaxin balalari islemir da u sikimsonic zibil
