### ISSUE TITLE
Can't download source from tests with grader because the link to the file has the wrong extension

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#1179]
## Issue template

**Description:** 

Downloading the source code from tests with grader fails with Error 500 because they have the wrong extension, `task.%25l` instead of `task.cpp`. Note that changing manually the extension to the correct one (`%25l` -> `.cpp`) the file is downloaded.

**Steps to reproduce:**

1. apply the patch as in #1153.
2. upload a test for a task with a grader, `ìnput.txt`, `task.cpp`, `grader.cpp`.
3. try to download the source of the task.

![Laboratoriodialgoritmi—MozillaFirefox_2021-05-15_00:38:51](https://user-images.githubusercontent.com/367272/118338262-fab46880-b515-11eb-96df-c7d083a795ff.png)

**Expected:**

The source code of the test (`task.cpp`) is downloaded.

**Actual:**

The server responds with a 500 error because the link is incorrect. In the example:
```
http://<domain.tld>/tasks/tsp/tests/1/files/tsp.%25l
```

![Error500—MozillaFirefox_2021-05-15_00:39:00](https://user-images.githubusercontent.com/367272/118338371-4830d580-b516-11eb-8227-8d46dab47b94.png)

instead of:
```
http://<domain.tld>/tasks/tsp/tests/1/files/tsp.cpp
```

Changing the link works and the file is downloaded:

![Workspace1_2021-05-15_00:43:31](https://user-images.githubusercontent.com/367272/118338500-9c3bba00-b516-11eb-99d8-df045ebd059a.png)

### Logs

From `/var/local/log/cms/ContestWebServer-0`: [2021-05-15-00-04-07.log](https://github.com/cms-dev/cms/files/6481483/2021-05-15-00-04-07.log)

### System Information

**CMS version:** [master, or a specific version]
**Was CMS installed:** yes, system-wide
**Using a virtualenv:** no
**Postgres version:** not relevant
**Distribution and version:** Ubuntu 20.04.2 LTS

**Comment by andreyv** [comment]
The immediate problem should be fixed in dbd6645ed82cce95b8b2a9c99f328669a2040887 by @ranaldmiao.

Note, however, that I couldn't reproduce the HTTP 500 status with CMS master. Out of interest, which `python3-xdg` Ubuntu package version do you have?

Anyway, applying the above patch should fix the problem in any case. You can test the patch with your installation.

**Comment by CristianCantoro** [comment]
> The immediate problem should be fixed in [dbd6645](https://github.com/cms-dev/cms/commit/dbd6645ed82cce95b8b2a9c99f328669a2040887) by @ranaldmiao.

Thank you.

> Note, however, that I couldn't reproduce the HTTP 500 status with CMS master. Out of interest, which `python3-xdg` Ubuntu package version do you have?

```bash
$ sudo pip3 freeze | grep xdg
pyxdg==0.25
```
(I have CMS installed system-wide)

**Comment by andreyv** [comment]
@CristianCantoro Were you able to test the patch with your installation? Does it work?

**Comment by CristianCantoro** [comment]
@andreyv said:
> @CristianCantoro Were you able to test the patch with your installation? Does it work?

Yes, I confirm that I was able to patch my installation and it works. Thank you, @andreyv.
