### ISSUE TITLE
Ability to delete Contests, Tasks, Users, and Submissions

### ISSUE THREAD

**Issue by shanehsu** [cms-dev/cms#118]
Currently, I can only delete test cases for tasks which bothers me a lot since I do a lot of misclick each day.

I would like to have buttons to delete all these other type of objects.

**Comment by lerks** [comment]
As mentioned, there are scripts `cmsRemove(Contest|Task|User|Participation|Submissions)` that achieve this and for all of them except submissions there is a button now to remove them through AWS. It was already brought up that removing submissions is a strange (and dangerous!) situation, so I'm personally fine with this situation. Closing.
