### ISSUE TITLE
Use one file cache per machine instead of per service

### ISSUE THREAD

**Issue by fagu** [cms-dev/cms#1182]
CMS currently uses one file cache per service (by default located in a directory below `/var/local/cache/cms/`). Each worker caches its own copy of each test case file, so if there are W workers on a machine and the total size of the test case files is S, the total disk space used is (eventually) at least W*S. On top of that, there are for example solution executables, etc. This recently caused us to run out of disk space in a contest with lots of workers (about 30) running on the same (powerful) machine. Our temporary solution during the contest was to repeatedly manually shut down some workers, delete their cache directories, and restart them.

Investigating this, @magula and I also discovered that there is code in the Workers https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/service/Worker.py#L67 and the ES https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/service/workerpool.py#L176 that supposedly precaches all files related to the configured contest when a worker connects. (This could speed up grading the first few submissions.) However, this code is never called because ES ignores the `contest_id`! The `ask_contest` parameter is not passed to `default_argument_parser`:
https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/scripts/cmsEvaluationService#L41 (We were in fact lucky that workers didn't precache files, as otherwise deleting a worker's cache directory would not have helped very much in our situation!)

Here are some approaches to reduce disk space consumption. I would be interested to hear your thoughts.
1. @t-lenz suggested a panic button that automates our temporary solution. ;)
2. Have all services on a machine share a cache directory. I think one would at least need to replace https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L571 with something that atomically moves the temporary file fetched from the database to its final destination if that destination file doesn't exist, and otherwise deletes the temporary file. (Maybe `renameat2` with the `RENAME_NOREPLACE` flag?) I suspect that otherwise there could be issues if one service replaces the file while another is reading from it. Also, I didn't look for additional potential problems. In any case, this approach still wastes resources (network traffic and CPU) as multiple services may simultaneously fetch the same file from the database.
3. Have all services on a machine share a cache directory and use a locking mechanism to ensure no two services fetch the same file at the same time. One would need a way to deal with stale locks from services that crashed while fetching a file.
4. Introduce a `FileCachingService` (FCS) with its own cache directory. At most one FCS can be configured to run on any machine. When a service would like to fetch a file, it requests it from the FCS running on the same machine via RPC (through a new `FileCacherBackend`). FCS uses its own internal locking mechanism to ensure no file is downloaded twice. To find out whether a file is in the cache and to read a cached file, it is not necessary to contact the FCS. (Just look for the file directly.) For backwards compatibility, if there is no FCS configured to run on the machine, use one cache directory per service. As far as I see, the process of fetching a file from the database is non-blocking, https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L66 so we should be fine even if multiple services concurrently request large files. One could perhaps have a script that asks FCS to precache all files related to a given contest and/or always have FCS precache all files related to the `contest_id` command line argument (similar to what ES was trying to do). Services would need to somehow deal with FCS shutting down at any point.

**Comment by fagu** [comment]
My apologies, I just realized after submitting that there was already an issue for this: https://github.com/cms-dev/cms/issues/154

**Comment by fagu** [comment]
Thanks for the very helpful feedback! I agree with your reasoning and am also in favor of 2. The main reason that multiple workers simultaneously fetch the same file (excluding pre-caching) is perhaps that ES simultaneously asks multiple workers to evaluate the same submission (on different test cases). They would simultaneously fetch the same executable file. This indeed doesn't seem like a big deal. :)

It now looks to me like the code would already almost* work if we simply have every `FileCacher` use the same directory (e.g. by removing the `-%s-%d` part in line 525). After all, the `load` function also uses an atomic rename (line 571) to store the downloaded file at its final destination, just like `FSBackend` does. Am I overlooking something?
https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L517-L526

# Read/move race conditions

Originally, I was worried about the following scenario: Worker A fetches a file and opens it for reading. Then, worker B fetches the same file and replaces the original one. Then, worker A continues reading from the original file (which has been replaced) and fails.

However, I now learned that the original file's inode is not actually deleted before all file handles referring to it have been closed. So worker A can in fact continue reading the original file, even after it has been replaced.

# Delete race conditions

Furthermore, there would be potential race conditions if a cached file is deleted (e.g. via the `drop` function) after we check whether a file exists in the cache in https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L599 but before we open it in
https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L607

Here are the functions that delete a file (or the entire cache directory):
- `drop`: never called directly
- `delete`: called in `cmstestsuite/unit_tests/db/filecacher_test.py` and `cmscontrib/CleanFiles.py`
- `destroy_cache`: only called in `cmstaskenv/Test.py`
- the atexit handler in line 521
- `check_backend_integrity`, but only if a file in the database has a wrong digest. This shouldn't happen... Also, the function isn't called anywhere. :)

I suggest we only use a shared cache directory if `service is not None` (avoiding all cases mentioned above, which currently already use temporary cache directories). When using a shared cache directory, have dropping functions always raise an Exception instead of performing any work, so nobody can accidentally introduce any potential race conditions later on (just for safety).

# [*] Mkdir race conditions
The one other race condition I can see is this: Say two services simultaneously try to create the cache directory (line 526). The first one successfully creates the directory (line 51 below). Then, the second tries to create the directory and fails because it already exists (line 53), and immediately starts looking for and writing files in the cache directory. Only a bit later does the first service fix the cache directory's permissions in lines 58-60. I don't know if this race condition would actually cause any problems, but would be in favor of instead letting `prerequisites.py install` create the shared cache directory.
https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/util.py#L43-L65

**Comment by fagu** [comment]
Actually, it shouldn't be hard to allow deletion. (So your `tmpfiles.d` trick would become safe, for example.) Simply get rid of the call to `os.path.exists` in `get_file` like so:
```python
while True:
    try:
        return open(cache_file_path, 'rb')
    except FileNotFoundError:
        logger.debug("File %s not in cache, downloading "
                    "from database.", digest)

        self.load(digest)

        logger.debug("File %s downloaded.", digest)
```
(This would be an infinite loop if someone constantly keeps deleting the cached files. If we instead opened the temporary file in `load` before moving it to its final location, we could even "ensure" that a file isn't deleted before it's opened.)

The other call to `os.path.exists` (in `put_file_from_fobj`) is completely superfluous I think (we can always replace the file, even if it exists):
https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L741-L744

**Comment by andreyv** [comment]
> It now looks to me like the code would already almost* work if we simply have every `FileCacher` use the same directory

Indeed, this looks to be almost the case. The (atomic) rename itself is sufficient to implement the method. After reading this, it appears to me that the code in `FSBackend.commit_file()` actually does _too much_ work (except maybe to get the return value).

As you correctly noticed, there is a problem with patterns like
```python
if os.path.exists(path):
    open(path)
```
if the file is removed between the lines. See below for more on this.

Yes, once a file is opened, the file descriptor points to the inode and is counted as a link, so the file won't be removed even if there are no other links. So replacing the filename will not have any effect on already open file descriptors.

I agree that it makes sense to create the shared worker cache during installation.

>  I suggest we only use a shared cache directory if `service is not None`

This is good suggestion :) It's still worthwhile to encapsulate this code in a `is_shared()` function, and use it in places like `purge_cache()` and `destroy_cache()`—I don't think these functions make sense for a shared cache now.

I also agree that this code: https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L741-L744 can be simplified.

---

On deleting files from cache:

While not strictly necessary, I think it would be prudent to allow this. It would enable various maintenance actions while the system is running (like the one you initially described :) ), and in general make the cache more robust.

The solution you described is correct (ensure that we open the file and check if it exists in one atomic operation). I think the approach with returning a file object from `load()`, and documenting it in the function description, is much preferred to polling—it requires no iteration and doesn't have the infinite loop problem.

Here are one more place that is relevant: https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L560 If `load()` is to return a file object, this place should likely be refactored anyway. `if_needed=True` is used in `precache_files()`. In theory, that call can be just replaced with `get_file()` at the expense of one more `open()`/`close()` per file. Another, more efficient solution is to return `None` in such a case, but rename `if_needed` to something like `cache_only`.

Let me know what you think about these points.

**Comment by fagu** [comment]
Good ideas! I've done the changes in the pull request.

Following your suggestion, the `load` method now has a `cache_only` parameter that determines whether the downloaded file should be opened and returned. I've made the method private since its meaning has changed and because of the slightly strange semantics. Instead, the two cases `cache_only=True` and `cache_only=False` are exposed as separate methods `cache_file` and `get_file`.

It's now okay to delete the files in `/var/local/cache/cms/fs-cache-shared` at any time. However, one of course must not delete the files in the temporary subdirectories `/var/local/cache/cms/fs-cache-shared/_temp*`.

The shared cache directory is created on installation. I was unsure what to do if it doesn't exist at runtime. For now, it will also be created at runtime as before. This is consistent with the directories `config.temp_dir` and `config.cache_dir`, which are also created at runtime and suffer from the same potential race condition, I guess. BTW, I don't understand why we try to create the cache directory twice, although it of course doesn't hurt... https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L526 https://github.com/cms-dev/cms/blob/dbd6645ed82cce95b8b2a9c99f328669a2040887/cms/db/filecacher.py#L532-L533

**Comment by fagu** [comment]
As for precaching, I'm not sure how to implement the one-worker-does-it-all approach.

1. Does the first worker to connect to ES get the job? Or the first worker listed in `cms.conf` (every time it connects)?
2. If the first worker is disabled, should it still precache?
3. If ES is started with contest id 'ALL', should the worker precache files for all contests / just for contests that aren't over / for no contests?

If we want automatic precaching, it feels conceptually cleaner to run a PrecachingService on each (worker) machine... :)

On the other hand, using a separate script for precaching is very easy to implement. Furthermore:

4. It's then clear which contest(s) are being precached (specified when calling the script).
5. It's easy to tell when precaching has finished.
6. The admin can decide to not precache simultaneously on all worker machines so as not to overwhelm the database. (?)
7. One can precache without restarting ES or a worker.

Obvious downsides to using a separate script are:

8. It's more work for admins.
8. The admins could forget to run the script or might simply not know about it.

What do you think?

**Comment by andreyv** [comment]
Good points. One thing I'm thinking about is CMS setups with a lot of contests in the DB. Automatic pre-caching of all contest data could blow up easily, so, I think, it is safer to pre-cache only explicitly given contests (or only running contests, as you noted).

Even when running with one contest, I'm not sure actually that we can easily do any better in ES than asking every worker to pre-cache files: not all workers may be running on the same machine.

So, it seems, the current code in ES is mostly fine even for the shared setup. We could think how to improve it for the multi-contest case (maybe a `precache_files` config parameter, or something else).

With a `PrecachingService`, there is still a question: how does one command it to cache specific contests. The service would also do nothing most of the time. Indeed, it seems that an utility script may be better suited for such one-off actions (and it's easier to implement…). Adding a script doesn't necessarily mean that the method in ES should be removed.

Regarding discoverability, if we need to specify the contest id to precache anyway, then one idea may be adding the command to AWS. A contest page could have a "Pre-cache files" button, which would trigger the same ES code to message all workers.

Anyway, these are just some ideas. I agree that, if this worked automatically, it would be easier for the admins, so we may see if the current pre-caching code can be improved for multi-contest setups.

**Comment by fagu** [comment]
Wasn't your idea to let one worker per machine (= ip address?) do the precaching?

If we ask every worker, they'll presumably all fetch the same files at the same time, wasting network, cpu, io. (If we want to proceed without using locks, one way to somewhat alleviate the issue would be to have workers download the files in random order. It's not great, though. For example, if one file is larger than all others combined, the workers might still all end up downloading it.)

I agree with everything else. A button in AWS could be a good idea, too, especially if we could include some feedback when all files have been precached. (It always feels weird when I push a button and don't know whether it did anything. :D)

**Comment by andreyv** [comment]
> Wasn't your idea to let one worker per machine (= ip address?) do the precaching?

Sorry, I had somehow forgotten that workers can be on different machines. Yes, this was the idea, but with multiple machines in mind it becomes slightly less trivial.

It could still be implemented, e.g., by remembering the worker source IP address and asking only one worker per address to pre-cache files (ignoring a strange setup where one worker machine has multiple addresses). For example, the first one to connect, so that pre-caching is initiated as early as possible.

Then there are questions, what to do if a worker reconnects, or if not all workers connect at all. Hence the comment that the current implementation is "mostly" fine, since it seems more reliable and is not worse than master before a446dff6ff1ac61c29116b386bfaf6e56bbe746e.

Anyway, for this approach it looks like a good start would be to tell the first worker from a machine to connect (determining either from source IP address or from config, as you said) to pre-cache files, and store this per-machine information in ES.

---

Your comment about locking gave me a further idea… :) We're trying to effectively synchronize multiple `FileCacher`s remotely from ES. But why not let the `FileCacher`s synchronize amongst themselves for caching, and keep the implementation encapsulated?

For example, `FileCacher` could have `begin_cache()` and `end_cache()` functions (names could be better), under which one could call `cache_file()`.

`begin_cache()` would return true if the cache lock is acquired, and false otherwise. If the return value is false, the caching code would quit immediately. The lock could be as simple as opening a `cache_lock` file in the cache directory and using non-blocking exclusive `flock()`. If the process dies, the lock is released. If a worker reconnects after some time, caching will be initiated again.

One could say that this is similar to method 3 discussed above, but here other workers don't need to wait for the operation, and the locking algorithm is much simpler.

P.S. There is still a remaining question about pre-caching all contests. It could be handled separately.

**Comment by fagu** [comment]
Ah, your global locking idea simplifies things a lot! An implementation is in #1185.

**Comment by fushar** [comment]
Should PR #1185 have closed this issue? :)

**Comment by fagu** [comment]
I think it could be closed. (The only thing mentioned that we haven't implemented is precaching when no contest id is specified.)

**Comment by andreyv** [comment]
You're right, closing. The remaining part is only tangentially related to the main task in this issue.

And thanks for all the discussions :)
