### ISSUE TITLE
Please add debian/windows docs on installing/running CMS

### ISSUE THREAD

**Issue by rajin100000** [cms-dev/cms#1189]
**Is your feature request related to a problem? Please describe.**

I use windows 7 32 bit and I wanted to get cms, But I didn't find any docs on how to do that. Then I decided to install ubuntu, but the it requires 64 bit. So I thought I would install debian, but I also didn't find any docs on how to install/run cms in debian.
**Describe the solution you'd like**

I want a docs/tutorial on how to install/run cms in windows/debian.
**Describe alternatives you've considered**

I haven't find any alternative solutions for this yet.

**Comment by andreyv** [comment]
Hi,

CMS does not support Windows. It requires Linux to run. There are detailed installation instructions for Ubuntu at https://cms.readthedocs.io/. The same instructions should apply to Debian, perhaps with some minor differences.

Also, it is better to ask such questions on the mailing list or in the chat. See https://github.com/cms-dev/cms#support.

**Comment by rajin100000** [comment]
Can I use MSYS, Cygwin, WSL to get support of CMS? And I have installed all requirements in windows. Then how is it possible that cms doesn't support Windows?

**Comment by andreyv** [comment]
CMS, among other requirements, needs a Linux kernel that supports control groups and related facilities. Installing user-space dependencies is not sufficient.

Yes, you could use a virtual machine like WSL2 to run CMS. However, submission evaluations might be inconsistent in a VM. It is fine if you just want to try CMS, but likely not good enough for production use without special adjustments (such as CPU pinning).

WSL1 probably won't work as it doesn't support all Linux system calls.

Please use the mailing list or the Gitter chat for support questions.

**Comment by andreyv** [comment]
Installation instructions are available at https://cms.readthedocs.io/. Closing.
