### ISSUE TITLE
html comments are ignored on condition

### ISSUE THREAD

**Issue by kbokis** [cms-dev/cms#1220]
**Steps to reproduce:**
1. Go to task statements and press edit to start translating a task
3. insert an html comment like 

**Expected:**
Comment should be ignored in the preview and the pdf produced

**Actual:**
If comment has two consecutive LF (line feed characters) i.e paragraph break, comment is visible in the preview and pdf produced.
Otherwise, it is hidden. 

### Logs
-nothing important in there-

### System Information

**CMS version:** [master, or a specific version]
**Was CMS installed:** yes 
**Using a virtualenv:** no
**Postgres version:**
**Distribution and version:**

**Comment by magula** [comment]
Hi @kbokis, this issue doesn't seem to be about CMS. What you describe sounds like you're using the [IOI's task translation system](https://github.com/ioi/translation), so you'll probably want to raise the issue there.

**Comment by kbokis** [comment]
Thanks, I will. Sorry for not reporting earlier, there was an ongoing competition and time was limited
