### ISSUE TITLE
Show explicitly the requirements on the task short name [was: Worker failed to create sandbox]

### ISSUE THREAD

**Issue by shanehsu** [cms-dev/cms#164]
I got this error when testing submissions,

Worker failed on operation `job 'compile submission 2'' Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/cms/service/Worker.py", line 118, in execute_job_group task_type.execute_job(job, self.file_cacher) File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/cms/grading/TaskType.py", line 235, in execute_job self.compile(job, file_cacher) File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/cms/grading/tasktypes/Batch.py", line 143, in compile sandbox = create_sandbox(file_cacher) File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/cms/grading/TaskType.py", line 55, in create_sandbox sandbox = Sandbox(file_cacher) File "/usr/local/lib/python2.7/dist-packages/cms-1.1.0pre-py2.7.egg/cms/grading/Sandbox.py", line 220, in **init** "Failed to initialize sandbox (error %d)" % ret) SandboxInterfaceException: Failed to initialize sandbox (error 2) 

Is there anything related to configuration I should check?

**Comment by lerks** [comment]
Done in #738.
