### ISSUE TITLE
Implement automatic tokens

### ISSUE THREAD

**Issue by lerks** [cms-dev/cms#246]
In IOI 2013 there was detailed feedback on all submissions and they all counted towards the score. That happened automatically, without the contestants doing anything.
In CMS's terms, this would translate into "all submissions were automatically tokened". At the moment there's no configuration setting to achieve this. We need to add it.

I have a couple of uncertainties regarding its implementation:
- How does this new token mode combine with the other ones? (i.e. what happens if at contest level tokens are automatic whereas at task level they're not, and vice versa)
- Are Token objects explicitly created in the database, or will all the code that needs them act as if they existed?

**Comment by stefano-maggiolo** [comment]
Artem implemented a "score mode" functionality that allow this without creating token objects.
