### ISSUE TITLE
cmstestsuite should be able to handle submission with more than one file

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#27]
Currently, cmstestsuite.web.CWSRequest.SubmitRequest handles only strict programming tasks, meaning that it request only one filename, that gets posted as <task_short_name>.<language_extension>.

Apart from limiting the test capabilities of cmstestsuite, this makes impossible to replay a contest with task types different from the most boring one.

**Comment by lerks** [comment]
Appears to have been done in a456f364f1c704208608f0e06be376b0f7a96f14. Closing.
