### ISSUE TITLE
Plugin system for programming languages

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#280]
We added support for several programming languages, but since everybody has their favourite, it doesn't seem feasible to accept all requests for support. With a plugin system, similar to what we have for task and score type, we could share the support for a language in an easy and non-invasive way.

Also, it would be nice to have a new repository for these plugins, if there is enough request.

**Comment by lerks** [comment]
I believe this was done in #693, closing. (Reopen if I'm wrong.)
