### ISSUE TITLE
Could CMS treat grader.o as grader.cpp?

### ISSUE THREAD

**Issue by kc97ble** [cms-dev/cms#299]
In IOI 2005, problem Rectangle, testdata contain following files: creclib_cpp.o, creclib.h, some inputs, outputs, and some other files. To compile a solution, we must execute g++ -static -O2 foo.cpp creclib_cpp.o. But I can't let CMS compile solution with .o file.

I have some ideas to resolve this problem:
- CMS should have a file list, and each item in this list should be in compilation's parameter.
- CMS should be able to accept executable file (this should be helpful in traning/unofficial contests).
- CMS should let administrator adjust compile command.

**Comment by stefano-maggiolo** [comment]
With commit 4ceb6446d121ef3febecdbad1710fe6c5f30b760 now .o managers are copied in the sandbox for compilation. It's the admins' duty to make sure compilation works correctly.

Again, this is not the best solution which should come from #152 :)
