### ISSUE TITLE
Password Protection for AdminServer

### ISSUE THREAD

**Issue by yangshun** [cms-dev/cms#317]
Is there a built-in way to add user/password protection for the AdminServer? It seems pretty necessary but there's no mention of it in the docs. Am I missing out on something?

**Comment by Bosco89** [comment]
As users and contestants are now separate entities, this should be easier to implement. It's also a good occasion to consider the creation of multiple administrative roles.

**Comment by karliss** [comment]
Basic admin accounts are implemented. Further discussions can be done in separate issues. This one can be closed.
