### ISSUE TITLE
Prominent warning when using keys and passwords in cms.conf.example

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#326]
AWS could display a warning band when the secret_key or the RWS credentials are the same as in the example configuration, to make sure that changing them is not overlooked by admins.

**Comment by giomasce** [comment]
+1

**Comment by stefano-maggiolo** [comment]
A warning is displayed in all of AWS pages. 4a31176ac92e9daacbf34cb74c86731ee2062942
