### ISSUE TITLE
Nginx and RWS

### ISSUE THREAD

**Issue by onursigirci** [cms-dev/cms#355]
I'm using nginx. 
RWS status is green("You are connected to the server and are receiving live updates.") only one computer. 

In all other computers, RWS status is yellow ("You are disconnected from the server but your browser is trying to connect.") I need to manually refresh for new information.

I didnt understand why. Could you help, please?

---- nginx.conf ---- RWS part

```
location ^~ /rws/ {
            proxy_pass http://rws/;
            include proxy_params;
            proxy_redirect http://$host/ /rws/;
            proxy_redirect https://$host/ /rws/;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            # Buffering blocks the streaming HTTP requests used for
            # live-update.
            proxy_buffering off;

            # Protect it with an authentication. For more information
            # see http://wiki.nginx.org/HttpAuthBasicModule.
            auth_basic "RankingWebServer";
            auth_basic_user_file /etc/nginx/htpasswd_RWS;

            # Protect it with an IP address whitelist.
            #allow 127.0.0.1;
            # Insert other allowed IP addesses or subnets here.
            #deny all;
        }
```

**Comment by lerks** [comment]
Sorry for the very late reply: I haven't been active for quite a while. If this is still an issue please do the following to help us diagnose it. Try to connect directly to the RWS, without passing through nginx. Does the behavior that you described still happen? If so, it's either the fault of RWS or of your browser and, thus, it would be helpful if you could post the log of RWS and the messages in the JS console of your browser. If it doesn't happen anymore then it's likely to be a nginx issue: could you please give us the full configuration file?

**Comment by lerks** [comment]
No response in over 2 years, closing.
