### ISSUE TITLE
Two or more contests in parallel

### ISSUE THREAD

**Issue by ashikoff** [cms-dev/cms#362]
It is me again :)
I'm trying to implement CMS as main contest system in Bulgaria replacing our SMOC and questions arise one after another. Here is very important one:

Can I start more than one contest on the same server? In SMOC I'm configuring all the contests for that particular competition (usually 5 competition groups - A, B, C, D, E - A being the eldest students and E is 11-12 yo). And then start them all when time comes. In CMS it seems (at least initially) that I can start only single contest (despite being able to configure more than one with it's own users, tasks and so on).

HELP ME!!! It will be really hard to supply at least 5 grading machines for each contest (and some reserves on top of that)

**Comment by andreyv** [comment]
@wil93 I use this patch now to "fix" this problem: https://gist.github.com/andreyv/1145f015cf88c9ddd2e89e159052db57.

**Comment by wil93** [comment]
@andreyv I am using the patch in PR #594

**Comment by andreyv** [comment]
@wil93 Interesting. Does this actually mean that CWS is the only one remaining service that does not support multiple parallel contests?

I recently tried starting the main services one by one and indeed only ContestWebServer wanted a contest id; others did not. Though I did not verify yet that this configuration actually works.

**Comment by wil93** [comment]
There is also ProxyService, but it's a minor issue (and it would require some radical changes to fix, like putting the ranking URL in the db instead of cms.conf)
