### ISSUE TITLE
Decouple programming languages and compiler

### ISSUE THREAD

**Issue by artikz** [cms-dev/cms#381]
Now CMS has only one compiler per programming language. But sometimes it's useful to have several compilers. For example if one would want to provide both C++03 and C++11, or Python 2 and 3, or Java 7 and 8, he is not able to do this. Most contest management systems I've seen allow contestants to manually select compiler for each submission.

**Comment by wil93** [comment]
Is this issue already solved? @stefano-maggiolo

**Comment by stefano-maggiolo** [comment]
Yes.
