### ISSUE TITLE
Can't always logout from CWS in firefox

### ISSUE THREAD

**Issue by nir-lavee** [cms-dev/cms#386]
Hi,

Like the title says - when using firefox, after logging in as a contestant, pressing "logout" leaves me on the same page. Sometimes `Ctrl+F5` gives me the login screen, revealing I'm actually logged out, but sometimes not. Deleting the cookies doesn't seem to do anything.

I haven't been able to reproduce this in chrome. Any thoughts?

Thanks,
Nir

**Comment by lerks** [comment]
It could be a caching issue: Firefox's cache algorithm may be more "aggressive" than Chrome's one, thus showing you an old version of the page instead of refreshing it from the server. Unfortunately I don't know much on the matter, and also I wouldn't know what to tune in CMS to fix this behavior, as we leave decisions about cache headers to Tornado.

**Comment by lucach** [comment]
Mozilla _is_ more aggressive [1]. At the moment we set the following cache-headers [2]:
`self.set_header("Cache-Control", "no-cache, must-revalidate")`

As the expiration time is not set, a heuristic algorithm is used (more or less the one described in RFC 2616 13.2 [3]). I think that this may lead to the problem described above.

[1] = https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_FAQ
[2] = https://github.com/cms-dev/cms/blob/master/cms/server/ContestWebServer.py#L127
[3] = http://tools.ietf.org/html/rfc2616#section-13.2

**Comment by lerks** [comment]
Thanks for the precise references!

[1] states that Firefox won't serve a document whose expiration time has passed, and that "Cache-control: no-cache" causes this time to always be in the past. Moreover any document with "Cache-control: must-revalidate" will always be revalidated with the server. Thus, as far as I can understand, with the header we add Firefox should behave correctly. The only "mistakes" I can come up with are that either the uppercase "C" in "Control" or the fact that we chain the two directives confuse Firefox, but it seems very unlikely. Do you happen to have any more pointers?

**Comment by lucach** [comment]
HTTP/1.1 headers are case-insensitive (same RFC, section 4.2).

**Comment by lucach** [comment]
However all this is very strange. `CTRL+F5` already forces Firefox to override the cache.

**Comment by giomasce** [comment]
As a humble suggestion, it may be worth a try to capture the network traffic in order to check whether the responsibility lies on the browser or on CWS.

**Comment by nir-lavee** [comment]
Thanks for the details everyone. If this is a firefox bug I am of course happy to leave it alone, but I thought I might as well post some more information:

I noticed a similar problem when logging in (again, only firefox, on several machines): I type the correct username and password, press log in, and firefox stays on the login page. Sometimes a "Login failed" message appears on the top right, sometimes not. In all cases I triple checked the username and password. Other times it works normally.

@giomasce When the problem occurs, I press log out, and the network tab in firefox's built in tool is empty. The status bar says "No requests". Ctrl+F5 keeps me logged in. Does this help by any chance?

**Comment by giomasce** [comment]
@nir-lavee My suggestion was about capturing the network traffic with some tool like Wireshark. That way you are sure of what is happening exactly between the server and the browser.

**Comment by nir-lavee** [comment]
@giomasce Okay, I will try to get around to it soon.

Meanwhile, it happened on Chromium too, but reproducing it seems harder and less consistent. Another strange thing, probably related, happened on Chromium: after logging out from "user4" and in to "user6", I have somehow gotten a situation where a problem's statement displays "Logged in as user6" at the top, while the problem's submissions displays "Logged in as user4". Pressing Ctrl+F5 fixed it so they are both user6.

I do not recall these issue from v1.0 in any browser (though that could be random chance). Has anything crucial changed in CMS cache-wise? I will also check if anything time/cache related changed on my server.

Thanks again.

**Comment by nir-lavee** [comment]
Disabling cache on the server's side seems to solve all problems mentioned. I don't know if that is advisable, but in any case the issue is probably with my particular setup - apologies for the confusion. Closing.

**Comment by lerks** [comment]
I'm glad to know that you resolved your issue.

Could you please tell us in greater detail what was happening and how you solved it? It may help other users. In particular, which server-side cache was active? Was it CMS or a transparent proxy you had set up (nginx)? Which setup did you have?
