### ISSUE TITLE
Getting error while building setup.py

### ISSUE THREAD

**Issue by TheStranger512** [cms-dev/cms#392]
I am following your documentation instructions about installing CMS on ubuntu (14.04), but i am getting error:
![screenshot from 2015-01-14 21 37 44](https://cloud.githubusercontent.com/assets/6565707/5743885/a7076994-9c35-11e4-9568-81cdd8097edd.png)
as you see in that directory there really is cms directory, so what does terminal want?

**Comment by wil93** [comment]
Try:

    cd /home/user/Documents
    ./setup.py build

**Comment by TheStranger512** [comment]
Thanks very much! that worked!
