### ISSUE TITLE
Errors occur when changing the port of AWS

### ISSUE THREAD

**Issue by t1016d** [cms-dev/cms#404]
After installing CMS, and it working, I tried to change the listen port of AWS.
I followed the document.
First, I copied "examples/cms.conf.sample" to "examples/cms.conf".
Second, I changed the port number at line127 in cms.conf.
Third, I used "sudo ./setup.py install" to reinstall it.
I used the command "cmsAdminWebServer", and I got "A critical error has occurred :-(" on the webpage which should be the admin interface.

Here is the log file:https://github.com/t1016d/log/blob/master/AdminWebServer-0/1422519947.log
Please help me.

**Comment by stefano-maggiolo** [comment]
It looks like the problem is with connecting to the DB. Did you [configure it](https://cms.readthedocs.org/en/v1.1/Running%20CMS.html#configuring-the-db) and set the correct connection string in `cms.conf`?

**Comment by t1016d** [comment]
It works!
Thanks for your help.

**Comment by stefano-maggiolo** [comment]
No problem, feel free to post more questions on the [mailing list](http://www.freelists.org/list/contestms)!
