### ISSUE TITLE
No compiler output for failed python compilations

### ISSUE THREAD

**Issue by anted** [cms-dev/cms#405]
If contestants submits a python solution that doesn't compile (e.g. it has syntax errors), the compiler output is not shown. Instead, we get the output of the subsequent mv command. (e.g. /bin/mv: cannot stat `batch.pyc': No such file or directory).

I suppose that cms.grading.compilation_step wasn't updated properly when the switch to multiple compile commands happened: it should either collect the stdout/stderr of all commands or at least the first one. It only picks up the output of the last one now.

**Comment by stefano-maggiolo** [comment]
Thanks, I fixed it here: 42ee954fcc7a5b8e5d5b5c11867dc0ad5baa41b2
