### ISSUE TITLE
Bad link in readthedocs

### ISSUE THREAD

**Issue by h4tguy** [cms-dev/cms#407]
The isolate submodule is not included in the tarball linked by http://cms.readthedocs.org/en/v1.2/Installation.html at https://github.com/cms-dev/cms/archive/v1.2.0.tar.gz

**Comment by stefano-maggiolo** [comment]
You are right, that is the link to the tar that GitHub automatically creates and that doesn't contain the submodule.

Please use https://github.com/cms-dev/cms/releases/download/v1.2.0/v1.2.0.tar.gz - we will fix the link in the doc for the next release.
