### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by praveingk** [cms-dev/cms#410]
Hi,

I just pulled the latest CMS. I installed all the build essentials, and did following :: 

1) ./setup.py build    --  Was successful.

2) sudo ./setup.py install -- it stopped with the following error :+1: 
Installing cmsImporter script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/cms-1.3.0pre-py2.7.egg
Processing dependencies for cms==1.3.0pre
Finished processing dependencies for cms==1.3.0pre
creating user and group cmsuser.
copying isolate to /usr/local/bin/.
Traceback (most recent call last):
  File "./setup.py", line 344, in <module>
    install()
  File "./setup.py", line 286, in install
    root, 04750, group=cmsuser_grp)
  File "./setup.py", line 194, in copyfile
    shutil.copy(src, dest)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: './isolate/isolate'

Can someone please help me resolve this? Tried this on two machines, but ended up with the sam failure.

Thanks,
Pravein.

**Comment by stefano-maggiolo** [comment]
Hello Pravein, I just realized there is a missing step in the installation instructions, sorry about that.

Assuming that you downloaded the tarball that includes isolate, you need to go to its directory and compile it:
```bash
cd isolate
make all
cd ..
```

Keeping this open to fix the documentation.

**Comment by wil93** [comment]
@stefano-maggiolo that should automatically run when calling `./setup.py build`.

```python
    print("compiling isolate...")
    os.chdir("isolate")
    os.system("make")
    os.chdir("..")
```
 @praveingk are you sure that the isolate submodule has been pulled as well? Try running `git submodule update --init`

**Comment by praveingk** [comment]
Thanks for the comments. I think that part is now fine then.

However, when I initialize the DB i get the below error - 

postgres@mobtorrent:~$ cmsInitDB 
2015/02/27 18:10:57 - WARNING [None] No configuration file found: falling back to default values.
2015/02/27 18:10:58 - CRITICAL [None] Operational error while talking to the DB. Is the connection string in cms.conf correct?

The cms.conf file is located in cms/cms.conf . Still the same error.

Can you please let me know if there is any step I am missing?

Thanks,
Pravein

**Comment by wil93** [comment]
> Can you please let me know if there is any step I am missing?

Make sure to follow all the instructions [here](http://cms.readthedocs.org/en/v1.2/Running%20CMS.html#configuring-the-db) and then launch `cmsInitDB`.

**Comment by praveingk** [comment]
I had followed the exact steps - The config files are stored in cms/config/

~/cms/config$ ls
cms.conf  cms.conf.sample  cms.ranking.conf  cms.ranking.conf.sample  nginx.conf  nginx.conf.sample

followed by this I executed the following cmds -

sudo su - postgres
createuser cmsuser -P
createdb -O cmsuser database
psql database -c 'ALTER SCHEMA public OWNER TO cmsuser'
psql database -c 'GRANT SELECT ON pg_largeobject TO cmsuser'
cmsInitDB

2015/02/27 18:22:41 - WARNING [None] No configuration file found: falling back to default values.
2015/02/27 18:22:42 - CRITICAL [None] Operational error while talking to the DB. Is the connection string in cms.conf correct?

Do I need to copy the conf files to somewhere else?

Thanks,
Pravein.

**Comment by wil93** [comment]
The configuration file is automatically copied from `config/cms.conf` to a system location (something like `/usr/local/etc/cms.conf`, for some reason). The default configuration specifies this connection string:

```
"database": "postgresql+psycopg2://cmsuser:password@localhost/database"
```

So, if you didn't change that line, you should be correctly set up (database name: "database", user name: "cmsuser", password: "password").

It is possible that postgres is just not running. Check if it's running by issuing `service postgresql status`. If it's not, then you'll have to start it by issuing `service postgresql start` (you'll likely need sudo for this one).

**Comment by praveingk** [comment]
Hi WIlliam,

I changed the line in cms.conf 
"database": "postgresql+psycopg2://cmsuser:XXXX@localhost/database",

username and database name is maintained same as the commands mentioned earlier.

However, the warning is about the config file not found right?

**Comment by praveingk** [comment]
It worked after copying the cms.conf file to /usr/local/etc manually. Thanks a lot.

**Comment by wil93** [comment]
> However, the warning is about the config file not found right?

Oh, you're right, I didn't notice that warning.

Anyway, the configuration file [should be copied automatically](https://github.com/cms-dev/cms/blob/v1.2/setup.py#L288) when running `sudo ./setup.py install`:

Also, if you copy it manually, you can copy it to a "more standard" location like `/etc/cms.conf` and CMS [will search it there as well](https://github.com/cms-dev/cms/blob/v1.2/cms/conf.py#L134).

**Comment by wil93** [comment]
@praveingk if this issue is solved I think you can close it (being the issue submitter :smile:).

**Comment by giomasce** [comment]
I think that it is safe to close the issue. If the submitter has other comments, they can reopen.

**Comment by walissassi** [comment]
thank you i have the same problem but i get this error 
 WARNING [None]  I/O error while opening file /usr/local/etc/cms.conf: [EACCES] Permission denied
WARNING [None]  No configuration file found: falling back to default values.
i did the steps as mentionned in the docs but when i write the command cmsInitDB i got these warning
best reagrds

**Comment by wil93** [comment]
@walissassi you probably missed [this step](http://cms.readthedocs.org/en/v1.2/Installation.html#installing-cms).

> If you install CMS, you also need to add your user to the cmsuser group and logout to make the change effective:
> `sudo usermod -a -G cmsuser <your user>`
> You can verify to be in the group by issuing the command:
> `groups`

**Comment by walissassi** [comment]
i did it but the same problem

**Comment by wil93** [comment]
I don't understand: did you manually create `cms.conf` inside `/usr/local/etc`? Try to run the following command, it should return something like this:

```bash
$ ls -l /usr/local/etc/cms.conf
-rw-rw---- 1 cmsuser cmsuser 5672  8 mar 19.01 /usr/local/etc/cms.conf
```

As you can see the file should be owned by `cmsuser` and should have `rw-rw----` permissions. If your output is different (that is, permission/owner are different), run the following commands to fix:

```bash
$ sudo chown cmsuser:cmsuser /usr/local/etc/cms.conf
$ sudo chmod 660 /usr/local/etc/cms.conf
```

**Comment by stefano-maggiolo** [comment]
I'm not sure if nowadays this is still a thing, but you might need to logout of your x session for changes to your groups to take effect.

**Comment by FrancisSalvamante** [comment]
I have done all the instructions but still it gives: CRITICAL [None] Operational error while talking to the DB. Is the connection string in cms.conf correct?

How could I possibly fix this error? cms.conf and cms.rankings.conf are both located at /etc/. Adding to this, I did not change the database configuration file.

**Comment by wil93** [comment]
For now, CMS will search for configuration files in `/usr/local/etc/` first. If no configuration files are found, then it will search them also in `/etc/`. So:

1) Make sure that you are working with the same configuration files that CMS is reading. When you start a CMS command (e.g. `cmsLogService`) you can see which configuration file is reading:

```
2015/06/14 12:03:49 - INFO [None] Using configuration file /etc/cms.conf.
2015/06/14 12:03:49 - INFO [LogService,0] LogService 0 up and running!
```

2) Once you are sure that you're working with the correct config file, make sure that the connection string is correct:

```
    "_help": "Connection string for the database.",
    "database": "postgresql+psycopg2://your_username:your_password@localhost/your_database",
```

Where `your_username`, `your_password`, `your_database` were decided during [this phase](http://cms.readthedocs.org/en/v1.2/Running%20CMS.html#configuring-the-db) (if you left the documentation commands unchanged, then you'll have the username `cmsuser` and database name `database`).

3) Make sure that the postgres daemon is running. If you have systemd (ubuntu >= 15.04, archlinux) you can check with `systemctl status postgresql`. If you have ubuntu < 15.04 I think you can do `service postgresql status`. If the daemon is not running, repeat the command with `start` instead of `status` and use sudo.

**Comment by Mayank-** [comment]
I have followed all the above steps and made sure that cms.conf was in the correct place and was owned by cmsuser. However, when I run cmsInitDB, I get the following error: 

2015/09/09 18:11:11 - WARNING [None] I/O error while opening file /usr/local/etc/cms.conf: [EACCES] Permission denied
2015/09/09 18:11:11 - WARNING [None] No configuration file found: falling back to default values.
2015/09/09 18:11:11 - CRITICAL [None] Operational error while talking to the DB. Is the connection string in cms.conf correct?

I have looked at the cms.conf file and it has the lines specified in the above comments. How do I resolve this issue.

**Comment by wil93** [comment]
@Mayank- what is the output of:

```bash
$ ls -l /usr/local/etc/cms.conf
```

Also, is your user in the `cmsuser` group? What's the output of:

```bash
$ groups
```

Also: if you put yourself in the cmsuser group, did you log out to make the change effective?

**Comment by Mayank-** [comment]
For the first question, I get the following output: 
-rw-rw---- 1 cmsuser cmsuser 5672 Sep  9 17:43 /usr/local/etc/cms.conf

For the second question, I get the following: 
postgres ssl-cert

**Comment by wil93** [comment]
Ok, you should then run this command to add yourself to the cmsuser group:

```bash
$ sudo usermod -a -G cmsuser your_user_name
```

(change `your_user_name` with the name of your user account, the one that you get with `echo $USER`)

And then log out to make the change effective.

**Comment by YRUDancin** [comment]
Hello, I am having the same issues... I used the default values: 
The CMS user is called "cmsuser"
The Database user is called "postgres"
and the database is called "cmsdb"
the password is "abcdefg"
Therefore, the connection string goes something like this: 
"database": "postgresql+psycopg2://cmsuser:abcdefg@localhost/cmsdb"

However, I am getting the same errors as described above:
WARNING [<unknown>] I/O error while opening file /usr/local/etc/cms.conf: [EACCES] Permission denied
and more.

My computer's user is part of the cmsuser group.
The permissions to the cms.config file is: -rw-rw---- 1 cmsuser cmsuser 5762 Apr 20 23:22 /usr/local/etc/cms.conf
which seems to agree with the above comments.

**Comment by YRUDancin** [comment]
Never mind... I figured it out...

I used `$ sudo usermod -a -G cmsuser postgres`
to add postgres to the cmsuser group
