### ISSUE TITLE
CMS doesn't work with MySQL db

### ISSUE THREAD

**Issue by caphindsight** [cms-dev/cms#413]
cms.conf connection string:

    "database": "mysql://cmsuser:<password>@localhost/cmsdatabase"

When I run cmsInitDB, I get the following error:

    sqlalchemy.exc.CompileError: (in table 'fsobjects', column 'digest'): VARCHAR requires a length on dialect mysql

**Comment by lucach** [comment]
http://cms.readthedocs.org/en/v1.2/Introduction.html#general-structure

> The state of the contest is wholly kept on a PostgreSQL database. At the moment, there is no way to use other SQL databases, because the Large Object (LO) feature of PostgreSQL is used. It is unlikely that in the future we will target different databases.

**Comment by caphindsight** [comment]
Ok thanks
