### ISSUE TITLE
Error occurring when submit a source code

### ISSUE THREAD

**Issue by ConanKun** [cms-dev/cms#427]
Hi, I finally installed cms, set problems, and conducted a test, but I encountered a trouble.

when I submitted a code, it said as follows

-----------
An error occured while the server was handling your request.

Note that attempts to tamper with Contest Management System (such as probing the server with customized URLs) may be considered cheating and may lead to disqualification.

If you encountered this error during normal usage, please notify the contest administrators.

-----------

what can be a reason(s) for the problem?

I set all informations(Time Limit, Memory Limit, etc), and uploaded all test datas.

when I go back to submissions tab, it says my code is still in compiling.

**Comment by wil93** [comment]
Are there active workers? Which processes did you start, beside cmsContestWebServer?

**Comment by ConanKun** [comment]
I'm now running cmsAdminWebServer, cmsRankingWebServer, cmsContestWebserver simultaneously.

**Comment by wil93** [comment]
Terminate cmsContestWebServer, and then start:

    cmsResourceService -a

which will automatically spawn cmsContestWebServer, cmsEvaluationService, cmsScoringService, cmsWorker, cmsProxyservice.

**Comment by ConanKun** [comment]
new error when execute cmsResourceService -a

Traceback (most recent call last):
  File "/usr/local/bin/cmsResourceService", line 5, in <module>
    pkg_resources.run_script('cms==1.2.0', 'cmsResourceService')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/EGG-INFO/scripts/cmsResourceService", line 77, in <module>
    sys.exit(0 if main() is True else 1)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/EGG-INFO/scripts/cmsResourceService", line 63, in main
    contest_id=ask_for_contest()).run()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/ResourceService.py", line 103, in __init__
    self._store_resources(store=False)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/ResourceService.py", line 312, in _store_resources
    vmem = psutil.virtual_memory()
AttributeError: 'module' object has no attribute 'virtual_memory'

how can i set virtual_memory attribute?

**Comment by wil93** [comment]
I think this is problem is similar to the `gevent` one. What version of `python-psutil` do you have? I guess 0.4 since you're probably on Ubuntu 12.04. You should upgrade to at least `python-psutil` 0.6 :smile:

**Comment by ConanKun** [comment]
now I have no troubles with cmsResourceService, but problem when submit a code still persist.. what should I do?

**Comment by wil93** [comment]
Start `cmsLogService`, see if there are errors when submitting.

**Comment by ConanKun** [comment]
these kinds of logs continuously show up.

2015/05/29 23:04:30 - INFO [LogService,0] Terminated connection with 127.0.0.1:52918: Connection closed.
2015/05/29 23:04:31 - WARNING [ContestWebServer,0] No allowed localization matches any installed one.Resorting to en-US.
2015/05/29 23:04:31 - INFO [AdminWebServer,0] Supported locales: [u'bs', 'en_US', u'et', u'fr', u'it', u'ja', u'lt', u'nl', u'ru', u'zh']
2015/05/29 23:04:34 - INFO [ResourceService,0] Restarting (PrintingService, 0)...
2015/05/29 23:04:34 - INFO [ResourceService,0] Restarting (ProxyService, 0)...
2015/05/29 23:04:35 - INFO [LogService,0] Established connection with 127.0.0.1:52982.
2015/05/29 23:04:35 - INFO [ProxyService,0] Initializing rankings.
2015/05/29 23:04:35 - ERROR [ProxyService,0] Cannot decode score type parameters.
ValueError('No JSON object could be decoded',).
2015/05/29 23:04:35 - WARNING [LogService,0] Failed reading from socket: [Errno 104] Connection reset by peer.
2015/05/29 23:04:35 - INFO [LogService,0] Terminated connection with 127.0.0.1:52982: Read failed.
2015/05/29 23:04:35 - INFO [EvaluationService,0] Found 0 missed operation(s).
2015/05/29 23:04:39 - INFO [ResourceService,0] Restarting (PrintingService, 0)...
2015/05/29 23:04:39 - INFO [ResourceService,0] Restarting (ProxyService, 0)...
2015/05/29 23:04:39 - INFO [LogService,0] Established connection with 127.0.0.1:53046.
2015/05/29 23:04:39 - INFO [ProxyService,0] Initializing rankings.
2015/05/29 23:04:39 - ERROR [ProxyService,0] Cannot decode score type parameters.
ValueError('No JSON object could be decoded',).
2015/05/29 23:04:40 - INFO [LogService,0] Terminated connection with 127.0.0.1:53046: Connection closed.
2015/05/29 23:04:44 - INFO [ResourceService,0] Restarting (PrintingService, 0)...
2015/05/29 23:04:44 - INFO [ResourceService,0] Restarting (ProxyService, 0)...
2015/05/29 23:04:44 - INFO [LogService,0] Established connection with 127.0.0.1:53109.

**Comment by ConanKun** [comment]
and when I looked up why I failed to compile, I found this

cc1plus: error: unrecognized command line option ‘-std=c++11’

**Comment by wil93** [comment]
> cc1plus: error: unrecognized command line option ‘-std=c++11’

Mmm... this is tricky. Since you have Ubuntu 12.04, your `gcc` version is 4.6. You need version 4.8 (which is found in Ubuntu 14.04).

Or, if you don't desire C++11 support, you can change line 230 of `cms/grading/__init__.py` from this:

    command += ["-static", "-O2", "-std=c++11",

to this:

    command += ["-static", "-O2",

and then install again.

**Comment by stefano-maggiolo** [comment]
But fundamentally 12.04 is not supported anymore by CMS - you'll likely run in other problems later.

**Comment by ConanKun** [comment]
um.. then it's better to upgrade ubuntu to 14.04?

**Comment by wil93** [comment]
Well, it would be the easiest and safest path :smile:

**Comment by ConanKun** [comment]
I've upgraded to 14.04 but still stuck with error with different error messages.
2015/05/30 01:09:07 - ERROR [ContestWebServer,0] Uncaught exception POST /tasks/add/submit 
<tornado.wsgi.HTTPRequest object at 0xb528a66c>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/__init__.py", line 195, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/ContestWebServer.py", line 1184, in post
    encrypt_number(submission.id)))
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscommon/crypto.py", line 148, in encrypt_number
    return encrypt_string(hexnum, key)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscommon/crypto.py", line 93, in encrypt_string
    key = _get_secret_key_unhex()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscommon/crypto.py", line 63, in _get_secret_key_unhex
    return binascii.unhexlify(config.secret_key)
TypeError: Non-hexadecimal digit found
2015/05/30 01:09:07 - ERROR [ContestWebServer,0] Uncaught exception (TypeError('Non-hexadecimal digit found',)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/__init__.py", line 195, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/server/ContestWebServer.py", line 1184, in post
    encrypt_number(submission.id)))
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscommon/crypto.py", line 148, in encrypt_number
    return encrypt_string(hexnum, key)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscommon/crypto.py", line 93, in encrypt_string
    key = _get_secret_key_unhex()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cmscommon/crypto.py", line 63, in _get_secret_key_unhex
    return binascii.unhexlify(config.secret_key)
TypeError: Non-hexadecimal digit found

2015/05/30 01:09:07 - INFO [EvaluationService,0] Executing operation `compile on 8 against dataset 1'.
2015/05/30 01:09:07 - INFO [EvaluationService,0] Asking worker 0 to `compile on 8 against dataset 1' (0:00:00.136903 after submission).
2015/05/30 01:09:07 - INFO [Worker,0/compile submission 8] Starting job.
2015/05/30 01:09:07 - INFO [EvaluationService,0] Operation `compile on 8 against dataset 1' concluded successfully
2015/05/30 01:09:07 - WARNING [ContestWebServer,0] No allowed localization matches any installed one.Resorting to en-US.
2015/05/30 01:09:08 - ERROR [Worker,0] Compilation aborted because of sandbox error in `/tmp/tmpKPXZrq/tmp'.
2015/05/30 01:09:08 - INFO [Worker,0/compile submission 8] Finished job.
2015/05/30 01:09:08 - ERROR [EvaluationService,0] Worker 0 signaled action not successful.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Operation `compile on 8 against dataset 1' for submission 8 completed. Success: False.
2015/05/30 01:09:08 - WARNING [EvaluationService,0] Worker failed when compiling submission 8(1).
2015/05/30 01:09:08 - INFO [EvaluationService,0] Executing operation `compile on 8 against dataset 1'.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Asking worker 1 to `compile on 8 against dataset 1' (0:00:00.444864 after submission).
2015/05/30 01:09:08 - INFO [Worker,1/compile submission 8] Starting job.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Operation `compile on 8 against dataset 1' concluded successfully
2015/05/30 01:09:08 - ERROR [Worker,1] Compilation aborted because of sandbox error in `/tmp/tmpharsMU/tmp'.
2015/05/30 01:09:08 - INFO [Worker,1/compile submission 8] Finished job.
2015/05/30 01:09:08 - ERROR [EvaluationService,0] Worker 1 signaled action not successful.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Operation `compile on 8 against dataset 1' for submission 8 completed. Success: False.
2015/05/30 01:09:08 - WARNING [EvaluationService,0] Worker failed when compiling submission 8(1).
2015/05/30 01:09:08 - INFO [EvaluationService,0] Executing operation `compile on 8 against dataset 1'.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Asking worker 1 to `compile on 8 against dataset 1' (0:00:00.615539 after submission).
2015/05/30 01:09:08 - INFO [Worker,1/compile submission 8] Starting job.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Operation `compile on 8 against dataset 1' concluded successfully
2015/05/30 01:09:08 - ERROR [Worker,1] Compilation aborted because of sandbox error in `/tmp/tmpSTtajC/tmp'.
2015/05/30 01:09:08 - INFO [Worker,1/compile submission 8] Finished job.
2015/05/30 01:09:08 - ERROR [EvaluationService,0] Worker 1 signaled action not successful.
2015/05/30 01:09:08 - INFO [EvaluationService,0] Operation `compile on 8 against dataset 1' for submission 8 completed. Success: False.
2015/05/30 01:09:08 - WARNING [EvaluationService,0] Worker failed when compiling submission 8(1).
2015/05/30 01:09:08 - ERROR [EvaluationService,0] Maximum tries reached for the compilation of submission 8(1).

**Comment by wil93** [comment]
Wild guess: you changed your `secret_key` (in cms.conf) to some random string? In that case, you should use an *hexadecimal string*. To generate it, fire up a python shell and issue:

    >>> import cmscommon.crypto
    >>> cmscommon.crypto.get_hex_random_key()
    '9edb072afd723e5e9b724a9a38f98c1a'

**Comment by wil93** [comment]
Let us know if it worked :smile:

**Comment by ConanKun** [comment]
sry for being late.

I had changed secret_key to normal string, so I changed this to hexadecimal string.
however, I still have a problem.

It's about sandbox..

--log--
2015/05/31 16:54:57 - ERROR [Worker,1] Compilation aborted because of sandbox error in `/tmp/tmpxbDyrr/tmp'.
2015/05/31 16:54:57 - INFO [Worker,1/compile submission 12] Finished job.
2015/05/31 16:54:57 - ERROR [EvaluationService,0] Worker 1 signaled action not successful.
2015/05/31 16:54:57 - INFO [EvaluationService,0] Operation `compile on 12 against dataset 1' for submission 12 completed. Success: False.
2015/05/31 16:54:57 - WARNING [EvaluationService,0] Worker failed when compiling submission 12(1).
2015/05/31 16:54:57 - INFO [EvaluationService,0] Executing operation `compile on 12 against dataset 1'.
2015/05/31 16:54:57 - INFO [EvaluationService,0] Asking worker 1 to `compile on 12 against dataset 1' (0:00:00.302614 after submission).
2015/05/31 16:54:57 - INFO [EvaluationService,0] Operation `compile on 12 against dataset 1' concluded successfully
2015/05/31 16:54:57 - INFO [Worker,1/compile submission 12] Starting job.
2015/05/31 16:54:57 - ERROR [Worker,1] Compilation aborted because of sandbox error in `/tmp/tmp4Mzfq2/tmp'.
2015/05/31 16:54:57 - INFO [Worker,1/compile submission 12] Finished job.
2015/05/31 16:54:57 - ERROR [EvaluationService,0] Worker 1 signaled action not successful.
2015/05/31 16:54:57 - INFO [EvaluationService,0] Operation `compile on 12 against dataset 1' for submission 12 completed. Success: False.
2015/05/31 16:54:57 - WARNING [EvaluationService,0] Worker failed when compiling submission 12(1).
2015/05/31 16:54:57 - INFO [EvaluationService,0] Executing operation `compile on 12 against dataset 1'.
2015/05/31 16:54:57 - INFO [EvaluationService,0] Asking worker 1 to `compile on 12 against dataset 1' (0:00:00.466920 after submission).
2015/05/31 16:54:57 - INFO [Worker,1/compile submission 12] Starting job.
2015/05/31 16:54:57 - INFO [EvaluationService,0] Operation `compile on 12 against dataset 1' concluded successfully
2015/05/31 16:54:58 - ERROR [Worker,1] Compilation aborted because of sandbox error in `/tmp/tmpJlNH4J/tmp'.
2015/05/31 16:54:58 - INFO [Worker,1/compile submission 12] Finished job.
2015/05/31 16:54:58 - ERROR [EvaluationService,0] Worker 1 signaled action not successful.
2015/05/31 16:54:58 - INFO [EvaluationService,0] Operation `compile on 12 against dataset 1' for submission 12 completed. Success: False.
2015/05/31 16:54:58 - WARNING [EvaluationService,0] Worker failed when compiling submission 12(1).
2015/05/31 16:54:58 - ERROR [EvaluationService,0] Maximum tries reached for the compilation of submission 12(1).

**Comment by stefano-maggiolo** [comment]
Hello again. One thing that happens frequently is that the permissions for the sandbox (isolate) are wrong, or CMS is not executing the version you expect (maybe you have another copy locally that has not the required permissions). See https://cms.readthedocs.org/en/v1.2/Troubleshooting.html#sandbox for some other possible causes.

**Comment by mcroitor** [comment]
Hello,
i need your help :) I created a contest with 3 problems, 2 problems goes as well, but third does not accept compiles. LogService get the next error:

```
23:38:46	WARNING	EvaluationService,0		Worker failed when compiling submission 74(1).
23:38:46	ERROR	EvaluationService,0		Received error from Worker: `JobException: u'Worker failed.' Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request response["__data"] = method(**request["__data"]) File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/Worker.py", line 125, in execute_job raise JobException(err_msg) JobException: u'Worker failed.' '.
23:38:46	ERROR	EvaluationService,0		Worker,1 signaled RPC for method execute_job was unsuccessful: JobException: u'Worker failed.' Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request response["__data"] = method(**request["__data"]) File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/Worker.py", line 125, in execute_job raise JobException(err_msg) JobException: u'Worker failed.' .
23:38:46	ERROR	Worker,1		Worker failed.
```
And i don`t understand why it falls.
Thank you,

**Comment by wil93** [comment]
@mcroitor it's better to use [the chat](gitter.im/cms-dev/cms) for these questions :wink:. A possible explanation, I think, is that the 3rd task is using a checker, which fails for some reason. Can you share the task?

Also, take a look at `/var/local/log/cms/Worker-1/last.log` to see if there are more useful error messages

**Comment by stefano-maggiolo** [comment]
Clarified in chat :)
(task was not supposed to use grader and configuration was wrong, plus the always-confusing log messages)
