### ISSUE TITLE
PIP from Ubuntu 15.04 cannot be used to install CMS

### ISSUE THREAD

**Issue by artikz** [cms-dev/cms#438]
It stops with "ImportError: cannot import name 'IncompleteRead'".
Solution is here:
http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

Probably, it worths mentioning it in documentation

**Comment by stefano-maggiolo** [comment]
I find the same problem in 14.04, but Ubuntu updated the package for pip
and now it is solved. Looking at
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991 it seems
that the bug popped back for 15.04... strange.
