### ISSUE TITLE
Vulnerability of CSRF

### ISSUE THREAD

**Issue by magrady24** [cms-dev/cms#453]
Implements in some GET method handlers are used for non-readonly requests, which are vulnerability of CSRF. (uses POST method or validates referer)

e.g.
https://github.com/cms-dev/cms/blob/41ff834621001e8dae9abe4097f291c30d3a3f98/cms/server/admin/templates/task.html#L225

**Comment by stefano-maggiolo** [comment]
Completely agree! Some have been moved to DELETE methods, but we still haven't completed. Thanks for raising this!

**Comment by karliss** [comment]
Is anyone currently working on this? I was thinking of adding csrf protection provided by Tornado and going through all get requsts to see if there is anything dangerous left.

**Comment by stefano-maggiolo** [comment]
Nobody that I'm aware of. That would be great, thanks!

**Comment by karliss** [comment]
TODO:
- [x] enable Tornado CSFR protection and make required changes to all forms
- [ ] fix tests to prevent CSFR from being triggered
- [ ] convert remaining state modifying GET requests

**Comment by stefano-maggiolo** [comment]
Hi @karliss, I am going soon (today if I manage or later this week) to merge #633, which is relevant for this. I don't think it changes much on your TODO list, though, just wanted to let you know.

**Comment by karliss** [comment]
Most of the requests there are done using `CMS.AWSUtils.ajax_delete`, which I already updated. That shouldn't cause much problems. I expect more conflicts with #624, #594 and anything that adds new forms.

**Comment by lerks** [comment]
It looks like this has been fixed in #690. Is any item outstanding?
