### ISSUE TITLE
Remaining tasks for 1.3

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#460]
This is a list of the remaining bugfixes / minor features before releasing CMS 1.3. It is mostly about things discovered at the IOI. The release date is planned to be within August.
- [ ] [patch prosed] Merge IP autologin feature.
- [X] Accept the AWS pagination branch (which includes a refactoring of the reevaluation buttons).
- [X] Fix RWS initial loading of data.
- [X] Pick up partially evaluated submission in ES's sweep.
- [ ] [patch existing] Add an "invalidate outcome" to reevaluate without deleting the existing evaluations objects (and add relevant documentation).
- [X] Fix the participation password field in AWS (weird when None is selected).
- [X] Remove any mention of localization from AWS.
- [X] [patch presented] PS sends submissions before tasks in certain occasions (resulting in a 400 in RWS).
- [X] [not reproducible] Delete attachments redirects to a non-existing page in AWS.
- [X] [working as intended] Look at DumpExporter argument parsing ("-c <id> target" does not work).

There are also these three bigger topics, which may or may not end up in 1.3.
- [x] Think if there is a simple way to fix the evaluation_tries (which were not updated after the split of evaluations).
- [ ] Reinstate JobGroups, and use them to distribute more ESOperations to a Worker in case the queue is big.
- [ ] Check if enabling background judging on a hidden dataset with ES active causes problems.

**Comment by stefano-maggiolo** [comment]
Let's update this at < 2 months from the release (this does not include the PRs already in flight):

- [ ] Real Java support (status: patch existing, but needs improvements).
- [ ] Reinstate JobGroup (status: todo).
- [ ] Command line switch in ES to optimize for throughput or latency, i.e. whether to send one testcase at a time or all at once to workers (status: todo).
- [ ] Use a cache of recent workers results in ES and write to DB only every so often (status: patch existing, but needs improvements).
- [ ] Remove all checks for "job not done" in ES (status: waiting for other patches).

Nice to have, but not required, in reverse order of importance:
- [ ] A simple implementation of analysis mode.
- [ ] Reorganize cmscontrib, in particular differentiate between the scripts types (importing, inserting from command line, removing).
- [ ] RWS visualizations (PR in flight, but stalled).
- [ ] Admin account (PR in flight, but stalled).

**Comment by lerks** [comment]
1.3 has been released, this is obsolete.
