### ISSUE TITLE
Invalid field(s) AssertionError()

### ISSUE THREAD

**Issue by kamentk** [cms-dev/cms#466]
Hi. I am very new to contest preparation and I decided to start with CMS. 

After a bit struggle I finaly managed do install CMS on my computer. When I start AWS I go to interface that can create new contest. I fill all fields with the information needed and click "Submit Query" button. Then I get error

Invalid field(s)
AssertionError()

Also all fields are reset to the initial values and contest is not created. 

I searched a lot but I couldn't find out what causes the problem.

Any suggestions would be appreciated.

Thanks.
Kamen.

**Comment by stefano-maggiolo** [comment]
Hi Kamen, I'm sorry for the struggle (and also for not keeping the form values...)

I'm not sure of what could cause that (usually if you have an invalid field the second line should tell you what to fix). I fear it might be the effect of some dependency with the wrong version. To check that, please try this: go to the "create new contest" page, just write something in the first textbox (name) and click submit. 

That should be a valid contest, so any error probably means there is something wrong in your installation. Please let me know the result, and possibly if there is any interesting log in the console where you launched AWS (or in the output of LogServer).

Feel free to join https://gitter.im/cms-dev/cms to do some live debugging, if you want.

**Comment by kamentk** [comment]
Hi again. I tried to create contest only with the name field filled. I get the same error message again. 

There is nothing unusual in the terminal from which I start the AWS.  

Where I can find the output of LogServer?

Thanks.
Kamen.

**Comment by stefano-maggiolo** [comment]
[To get the logs from LogServer you just need to start it (in the same way of AWS). But they won't tell you more.]

Can I have some more info?
1. Are you running CMS as in the master branch, or some released version (1.2)?
2. How are you running CMS (installed, within a virtualenv, from the repository)?
3. How did you install the dependencies? Can you double check that the versions are compatible with CMS? See http://cms.readthedocs.org/en/latest/Installation.html#python-dependencies for the dependencied in case you are running from master, http://cms.readthedocs.org/en/v1.2/Installation.html#dependencies if you are running 1.2.

**Comment by kamentk** [comment]
I am running the stable version - 1.2.(master branch) I have followed all steps from cms.reathedocks.org and I have installed all dependencies with their last versions. I have rechecked all requirements and I have covered them.  I am instaling it directly on my Ubuntu 14.04. I am not using virtualenv(I am not shure what exactly it is for). 

Maybe I am not running CMS properly  or I haven't installed it properly.

**Comment by wil93** [comment]
If you run `pip list` what output do you see?

**Comment by stefano-maggiolo** [comment]
My associate @lerks suggested it could be that you're using a too-fresh version of Tornado (>= 4.2). This version introduced an assert that made visible a previously ignored error in our code. It was fixed in https://github.com/cms-dev/cms/commit/d64c8b35ef4e2eaf547621add319cf6ae9ecc311

You can try to patch in that change and see if it solves the problem (the other fix could be to downgrade Tornado to < 4.2). Hope this is really the problem, but it definitely looks like it.

**Comment by kamentk** [comment]
The output from pip list

adium-theme-ubuntu (0.3.4)
apt-xapian-index (0.45)
argparse (1.2.1)
backports.ssl-match-hostname (3.4.0.2)
BeautifulSoup (3.2.1)
certifi (2015.04.28)
chardet (2.0.1)
cms (1.2.0)
colorama (0.2.5)
command-not-found (0.3)
coverage (3.7.1)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
duplicity (0.6.23)
gevent (1.0.2)
greenlet (0.4.7)
html5lib (0.999)
httplib2 (0.8)
lockfile (0.8)
lxml (3.3.3)
mechanize (0.2.5)
mock (1.0.1)
MySQL-python (1.2.3)
netifaces (0.10.4)
oauthlib (0.6.1)
oneconf (0.3.7.14.04.1)
PAM (0.4.2)
Patool (1.4)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
psutil (1.2.1)
psycopg2 (2.4.5)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pygobject (3.12.0)
pyinotify (0.9.4)
pyOpenSSL (0.13)
PyPDF2 (1.25.1)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2015.4)
pyxdg (0.25)
PyYAML (3.10)
reportlab (3.0)
requests (2.2.1)
sessioninstaller (0.0.0)
setuptools (3.3)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
SQLAlchemy (1.0.8)
system-service (0.1.6)
tornado (4.2.1)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
unity-lens-photos (1.0)
urllib3 (1.7.1)
virtualenv (13.1.2)
Werkzeug (0.10.4)
wheel (0.24.0)
wsgiref (0.1.2)
xdiagnose (3.6.3build2)
zope.interface (4.0.5)

Yeah from this log we can see that my tornado version is 4.2.1 - greater than 4.2. I will try to patch it and will tell you what is the result.

**Comment by lerks** [comment]
Not having heard back from you, I assume you managed to fix the problem. Thus I close this issue. Feel free to reopen it if you have more questions.
