### ISSUE TITLE
ProxyService :  Cannot decode score type parameters.

### ISSUE THREAD

**Issue by Mr-Mowz** [cms-dev/cms#484]
Hi,

I've been trying to install CMS with no success. I tried it in two different machines but I keep getting the same error.
When running "cmsResourceService -a", it asks me to choose a contest and then it says :  

2015/10/15 22:20:03 - INFO [ResourceService,0] ResourceService 0 up and running!
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (AdminWebServer, 0)...
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (Checker, 0)...
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (ContestWebServer, 0)...
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (EvaluationService, 0)...
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (PrintingService, 0)...
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (ProxyService, 0)...
2015/10/15 22:20:03 - INFO [ResourceService,0] Restarting (ScoringService, 0)...
2015/10/15 22:20:04 - INFO [ResourceService,0] Restarting (Worker, 0)...
2015/10/15 22:20:04 - INFO [ResourceService,0] Restarting (Worker, 1)...
2015/10/15 22:20:04 - INFO [ResourceService,0] Established connection with 127.0.0.1:59973.
2015/10/15 22:20:04 - INFO [ResourceService,0] Established connection with 127.0.0.1:59983.
2015/10/15 22:20:08 - INFO [ResourceService,0] Restarting (ProxyService, 0)...
2015/10/15 22:20:13 - INFO [ResourceService,0] Restarting (ProxyService, 0)...

The fact that it keeps restarting ProxyService again and again, and thus the ranking is not working. 

So I tried to start ProxyService manually to see what's going wrong. 

Output for cmsProxyService :

2015/10/15 22:22:28 - INFO [ProxyService,0] Initializing rankings.
2015/10/15 22:22:28 - ERROR [ProxyService,0] Cannot decode score type parameters.
ValueError('No JSON object could be decoded',).
Traceback (most recent call last):
  File "/usr/local/bin/cmsProxyService", line 5, in <module>
    pkg_resources.run_script('cms==1.2.0', 'cmsProxyService')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/EGG-INFO/scripts/cmsProxyService", line 52, in <module>
    sys.exit(0 if main() is True else 1)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/EGG-INFO/scripts/cmsProxyService", line 47, in main
    ask_contest=ask_for_contest).run()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/util.py", line 228, in default_argument_parser
    return cls(args.shard, ask_contest())
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/ProxyService.py", line 267, in __init__
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/service/ProxyService.py", line 340, in initialize
    score_type = get_score_type(dataset=task.active_dataset)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/cms/grading/scoretypes/__init__.py", line 77, in get_score_type
    parameters = json.loads(parameters)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Any clue :-) ?

**Comment by stefano-maggiolo** [comment]
Hi,

it is embarrassingly badly reported, but this means that the string configuring the score type (i.e., if your score type is Sum, then it configures the maximum score, if it is Group<something> it configures the groups) cannot be parsed (it should be a serialized JSON object).

To fix it, start AdminWebService on its own (cmsAdminWebService), then go to the task, scroll down until you see Score type and Score parameters. If the Score type is GroupMin, for example, the Score parameters should be something like `[[10, 2], [15, 2], [20, 2], [25, 2], [30, 2]]` (which means that there are 5 groups, and the first has 2 testcases and passing it awards 10 points, and so on). If the Score type is Sum, the parameters should simply be a number (like `100`).

Does this solve your problem?

, and you can set it going to the AdminWebService, then to the task

**Comment by stefano-maggiolo** [comment]
Minor edit: for Sum the number is not the maximum score, but the score per-testcase.
