### ISSUE TITLE
Problem with cmsInitDB

### ISSUE THREAD

**Issue by alexbagirov** [cms-dev/cms#486]
Hello.

After creating a PostgreSQL database and user I run the following in my cms folder
```
cmsInitDB
```
and see this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/cmsInitDB", line 5, in <module>
    pkg_resources.run_script('cms==1.2.0', 'cmsInitDB')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2.0-py2.7.egg/EGG-INFO/scripts/cmsInitDB", line 34, in <module>
    import gevent.monkey
ImportError: No module named gevent.monkey
```

Currently I am trying to run it on C9. Probably that's why I get this error. Can you help me solving it please?

**Comment by lerks** [comment]
What distribution and which version of it are you running?

Do you have the `gevent` Python package installed, at a recent version (at least 1.0)?

**Comment by alexbagirov** [comment]
I am trying to install 1.2.0.

No, I haven't installed it manually. How can I check it?

**Comment by alexbagirov** [comment]
Oh, I've managed to setup it but it tells me I don't have some more modules. Is there a full list of those I have to have?

**Comment by giomasce** [comment]
Yes, it is written on the documentation: https://cms.readthedocs.org/en/v1.2/Installation.html#dependencies.

I close this issue, please reopen if the bug persists.
