### ISSUE TITLE
Worker Fails to Compile

### ISSUE THREAD

**Issue by nikhilhassija** [cms-dev/cms#496]
I've setup CMS 1.2 on my Ubuntu 14.02 LTS 64-bit system. I could get everything running, but the workers fail to compile the submission and raise the following error.

```
17:37:18	ERROR	EvaluationService,0		Received error from Worker: `JobException: u'Worker failed.' Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request response["__data"] = method(**request["__data"]) File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/Worker.py", line 119, in execute_job raise JobException(err_msg) JobException: u'Worker failed.' '.
17:37:18	ERROR	EvaluationService,0		Worker,1 signaled RPC for method execute_job was unsuccessful: JobException: u'Worker failed.' Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/io/rpc.py", line 382, in process_incoming_request response["__data"] = method(**request["__data"]) File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/service/Worker.py", line 119, in execute_job raise JobException(err_msg) JobException: u'Worker failed.' .
17:37:18	ERROR	Worker,1		Worker failed.
```

**Comment by wil93** [comment]
Do you have a more detailed log of the error inside `/var/local/log/cms/Worker-1/`?

Also, have a look at http://cms.readthedocs.org/en/v1.2/Troubleshooting.html#sandbox

**Comment by nikhilhassija** [comment]
I've tried all the mentioned fixed on troubleshooting page, `isolate` was already configured correctly. 

This is the last.log in `/var/local/log/cms/Worker-1/`
```
2015/11/16 09:53:09 - INFO [Worker,1] Worker 1 up and running!
2015/11/16 09:53:09 - INFO [Worker,1] Established connection with 127.0.0.1:50505.
2015/11/16 09:53:09 - INFO [Worker,1] Established connection with 127.0.0.1:50519.
2015/11/16 09:53:09 - INFO [Worker,1] Precaching files for contest 1.
2015/11/16 09:53:10 - INFO [Worker,1] Precaching finished.
2015/11/16 09:53:41 - INFO [Worker,1] Established connection with localhost:29000 (LogService,0).
2015/11/16 09:54:43 - INFO [Worker,1/compile submission 5] Starting job.
2015/11/16 09:54:43 - ERROR [Worker,1] Worker failed.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2-py2.7.egg/cms/service/Worker.py", line 109, in execute_job
    task_type.execute_job(job, self.file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2-py2.7.egg/cms/grading/TaskType.py", line 243, in execute_job
    self.compile(job, file_cacher)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.2-py2.7.egg/cms/grading/tasktypes/Batch.py", line 172, in compile
    job.managers["grader%s" % source_ext].digest
KeyError: u'grader.cpp'
2015/11/16 09:59:09 - WARNING [Worker,1] Worker,1 received request to shut down.
2015/11/16 09:59:09 - INFO [Worker,1] Worker 1 is shutting down
2015/11/16 09:59:09 - INFO [Worker,1] Terminated connection with localhost:29000 (LogService,0): Disconnection requested.
```

**Comment by stefano-maggiolo** [comment]
Hi Nikhil! This is because your task is configured to be a task with grader, but you didn't provide one. 

[Just to fix the naming (since every grading system has its own), for grader we intend a piece of code that is compiled with the contestant's solution, and usually provides the main function and I/O, and call the contestant-provided function.]

If you intended to have stand-alone submission, you can go to the task configuration page and select "Submissions are self-sufficient" instead; otherwise you need to provide a grader for each language your contest support. For an example you can see https://github.com/cms-dev/con_test/tree/master/batchgrader/sol

Hope this helps!

**Comment by wil93** [comment]
As Stefano said, from the new log provided it looks like the task needs a grader. Note that you should add a grader **for each language** you will support.

If, for example, you already provided a `grader.c` file, you should also add a `grader.cpp` file.

That is, you should go to the admin panel, open the task, scroll down to the active dataset, and click "Add a manager", and then select a grader.cpp file.

**Comment by nikhilhassija** [comment]
@stefano-maggiolo, I intended to use to the functionality what "Submissions are self-sufficient" option gave me. Although, the language got me confused between the options. Changing the compilation type fixed the issue. Thanks!
