### ISSUE TITLE
How can I totally remove CMS?

### ISSUE THREAD

**Issue by kc97ble** [cms-dev/cms#520]
It seems difficult to remove CMS completely. Could you show me the way to fully remove it? Thank you.

**Comment by wil93** [comment]
It depends on how you installed it. If you used the standard method (which is used up until version 1.2) then you should:

1. Remove the `cms` python module, which (until 1.2) had to be installed globally, so: `sudo pip uninstall cms`
2. Undo everything that's being done in these lines (from 266 to 233): https://github.com/cms-dev/cms/blob/v1.2/setup.py#L266L333

**Comment by stefano-maggiolo** [comment]
[I already started writing a detailed list of location before William answered, so let me finish...]

Hi! Here's a list of paths that CMS can touch during install or run:
```
/etc/cms*.conf
/usr/local/etc/cms*.conf
/usr/local/bin/cms*
/usr/local/bin/isolate
/usr/local/share/locale/*/*/*cms*
/var/local/cache/cms
/var/local/lib/cms
/var/local/log/cms
/var/local/run/cms
```
more in general, `/var/local/*/cms` and `/usr/local/*/cms`

Moreover, there are the Python installation files, which might be in 
```
/usr/local/lib/python2.7/dist-packages/*cms*
```
(or similar, depending on the distribution).

Finally, you may have something in `/tmp`, which should be removed at the next reboot, and the user/group cmsuser to remove manually.

**Comment by wil93** [comment]
Just to further clarify: the python-specific path (e.g. `/usr/local/lib/python2.7/dist-packages/*cms*`) is automatically removed when running `sudo pip uninstall cms`.

Also, note that the upcoming version of cms offers a [prerequisites.py](https://github.com/cms-dev/cms/blob/master/prerequisites.py) script which can be called like this:

    $ sudo ./prerequisites.py uninstall

And that will delete isolate, the localization and configuration files, and then will:

* Remove from the `cmsuser` group every user that belongs to it
* Delete the `cmsuser` group

**Comment by kc97ble** [comment]
Thank you very much!
