### ISSUE TITLE
cmsAddUser changed! How to use it in the latest version of CMS?

### ISSUE THREAD

**Issue by kc97ble** [cms-dev/cms#524]
I used to input something like this to add a new user:
cmsAddUser -c contestid -p password firstname lastname username

However, in the latest version of CMS, I can't do like that.
Could you tell me the right way to do?

**Comment by wil93** [comment]
You should create a contest.yaml file with the users, like [this](https://github.com/cms-dev/con_test/blob/master/contest.yaml).

Then, you can call:

    $ cmsAddUser u1

to add the user with username "u1", or:

    $ cmsAddUser --all

to add every user in the contest.yaml file

**Comment by wil93** [comment]
Note, however, that this will only create the users (they will not be attached to the contest).

The users will be attached to the contest when you call:

    $ cmsAddContest .

If you want to attach a user to an *existing* contest, I think that for the moment you can only do it with the web admin panel (click on the contest -> "Users" -> "Add a new user").

**Comment by kc97ble** [comment]
Thank you. I understand.
