### ISSUE TITLE
Need to add a thing into cms installation guide.

### ISSUE THREAD

**Issue by kc97ble** [cms-dev/cms#528]
Please add this line into the documentation of the latest version.

sudo apt-get install libffi-dev

**Comment by stefano-maggiolo** [comment]
Hi! Do you know which part requires this library? Do you only need it if you install the Python packages with pip?

Thanks

**Comment by wil93** [comment]
It's for compiling bcrypt (only when you use pip). If you're not using pip, it's OK to do `apt-get install python-bcrypt`

**Comment by kc97ble** [comment]
I saw an error (something like "ffi.h not found") when installing CMS with pip. Now I have installed CMS successfully , so there is no way for me to indicate where does the error come from.
