### ISSUE TITLE
What is the format of "Allowed web interface localization"?

### ISSUE THREAD

**Issue by kc97ble** [cms-dev/cms#529]
Assume that I only allow English and Vietnamese to be used in the CWS. What should I input in the box "Allowed web interface localization"?

**Comment by stefano-maggiolo** [comment]
Sorry for the confusion, indeed I had to try myself to find out...

It's a simple list of comma-separated locales without any quotes, so for example "en,vn" (without the quotes). I'll add an example in the interface.

PS: if you have Vietnamese localization, we'd like to include in the repository, feel free to send a PR or just drop the files at my email (s.maggiolo@gmail.com).

**Comment by stefano-maggiolo** [comment]
Oh, and one last thing, the list of locales does not update with the available locales, the only change is that an unavailable locale will revert to English when selected ... which makes it slightly useless I guess. Sorry.

**Comment by stefano-maggiolo** [comment]
Actually I don't have time to do it right now. Reopening this to track "better explanations of fields in AWS pages"
