### ISSUE TITLE
Problem running cmsWebServer

### ISSUE THREAD

**Issue by praveingk** [cms-dev/cms#531]
Hi,

I faced the below error when trying to run the cmsAdminwebserver.

 sudo cmsAdminWebServer &
[2] 27971
sadm@noi-2:~$ 2016-01-28 14:29:45,956 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2016-01-28 14:29:46,615 - INFO [Log,0] Established connection with 127.0.0.1:48972.
2016-01-28 14:29:46,616 - INFO [Admin,0] Established connection with localhost:29000 (LogService,0).
2016-01-28 14:29:46,630 - ERROR [Admin,0] Cannot create necessary directories.
2016-01-28 14:29:46,630 - ERROR [Admin,0] Cannot create necessary directories.
Traceback (most recent call last):
  File "/usr/local/bin/cmsAdminWebServer", line 4, in <module>
    __import__('pkg_resources').run_script('cms==1.3.dev0', 'cmsAdminWebServer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1636, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/EGG-INFO/scripts/cmsAdminWebServer", line 51, in <module>
    sys.exit(0 if main() is True else 1)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/EGG-INFO/scripts/cmsAdminWebServer", line 46, in main
    AdminWebServer).run()
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/util.py", line 230, in default_argument_parser
    return cls(args.shard)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/server.py", line 86, in __init__
    self.file_cacher = FileCacher(self)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/db/filecacher.py", line 428, in __init__
    raise RuntimeError("Cannot create necessary directories.")
RuntimeError: Cannot create necessary directories.

Can you please check.

Thanks,
Pravein.

**Comment by stefano-maggiolo** [comment]
PS: for help with installation and usage, please write to contestms@freelists.org.

Most probably you don't have permissions to write in /var/local/cache/cms, which I suspect is because you did not logout after installing cms (your user is inserted in the group cmsuser that owns that directory, but that has no effect until you log out and log back in). To confirm this, you can try:
- with ```ls -ld /var/local/*/cms``` make sure that it says that the owning group is cmsuser
- with ```groups``` make sure you see cmsuser in your groups.

**Comment by praveingk** [comment]
Thanks Stefano,
I checked that there is no cmsuser group. However, not sure why it is not
there.
I get this problem, even after running the setup install. Am I missing any
step?

sadm@noi-2:~/cms$ sudo usermod -a -G cmsuser sadm
usermod: group 'cmsuser' does not exist
sadm@noi-2:~/cms$

Thanks,
Pravein.

**Comment by praveingk** [comment]
Hi,

I created the group, and the directories. However, the error still persists.

sadm@noi-2:/var/local$ cmsAdminWebServer &
[2] 28612
*2016-01-28 16:54:17,820 - ERROR [Admin,0] Cannot create necessary
directories.*
Traceback (most recent call last):
  File "/usr/local/bin/cmsAdminWebServer", line 4, in <module>
    __import__('pkg_resources').run_script('cms==1.3.dev0',
'cmsAdminWebServer')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 1636, in run_script
    exec(code, namespace, namespace)
  File
"/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/EGG-INFO/scripts/cmsAdminWebServer",
line 51, in <module>
    sys.exit(0 if main() is True else 1)
  File
"/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/EGG-INFO/scripts/cmsAdminWebServer",
line 46, in main
    AdminWebServer).run()
  File
"/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/util.py",
line 230, in default_argument_parser
    return cls(args.shard)
  File
"/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/server.py",
line 86, in __init__
    self.file_cacher = FileCacher(self)
  File
"/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/db/filecacher.py",
line 428, in __init__
    raise RuntimeError("Cannot create necessary directories.")
RuntimeError: Cannot create necessary directories.
2016-01-28 16:54:17,874 - WARNING [Log,0] Failed reading from socket:
[Errno 104] Connection reset by peer.
2016-01-28 16:54:17,875 - INFO [Log,0] Terminated connection with
127.0.0.1:48975: Read failed.

[2]+  Exit 1                  cmsAdminWebServer
sadm@noi-2:/var/local$
sadm@noi-2:/var/local$
sadm@noi-2:/var/local$
*sadm@noi-2:/var/local$ ls -ld /var/local/*/cms*
*drwxrwsr-x 5 sadm cmsuser 4096 Jan 28 16:54 /var/local/log/cms*
*sadm@noi-2:/var/local$ groups*
*sadm adm cdrom sudo dip plugdev lpadmin sambashare cmsuser*
*sadm@noi-2:/var/local$ *

Thanks,
Pravein.

**Comment by stefano-maggiolo** [comment]
The setup install only deals with the python code. We have another script to do the rest, which is ```sudo ./prerequisites.py install``` (see http://cms.readthedocs.org/en/latest/Installation.html#installing-cms). This should create the group, and all necessary directories.

(In particular I think the problem is that you're missing /var/local/*/cms, with * being lib, cache, run)

**Comment by praveingk** [comment]
Thanks Stephano. After installing the pre-requisites that part seems fine.
I had run the adminwebserver.
However, I am not able to login to the adminwebserver remotely thru port
8889.

cmsAdminWebServer &
[1] 32326
sadm@noi-2:~$ 2016-01-29 09:39:58,521 - INFO [<unknown>] Using
configuration file /usr/local/etc/cms.conf.
2016-01-29 09:39:59,143 - INFO [Admin,0] Established connection with
localhost:29000 (LogService,0).
2016-01-29 09:39:59,160 - INFO [Admin,0] AdminWebServer 0 up and running!


However, I am not able to access it thru the webpage. Is there anything I
need to check

Thanks,
Pravein.

**Comment by wil93** [comment]
Check this section of your cms.conf file:

```
"_section": "AdminWebServer",

"_help": "Listening HTTP address and port for the AWS. If you access",
"_help": "it through a proxy running on the same host you could put",
"_help": "127.0.0.1 here for additional security.",
"admin_listen_address": "",
"admin_listen_port":    8889,
```

The "admin_listen_port" is the one that will be used when AWS is "up and running". Also, if you did put "127.0.0.1" in the "admin_listend_address" field then you won't be able to see AWS unless you are using the browser on the same machine that is running it.

**Comment by praveingk** [comment]
Thanks William,

I did check this section in cms.conf. And I changed admin_listen_address to
the ip address of the external network interface of the machine. However,
still not able to access it from other machines. However, i am able to
access the web page  from the local machine.

Is there any where else i need to change too?

Thanks,
Pravein.

**Comment by stefano-maggiolo** [comment]
To me it works as expected (in particular specifying a non-localhost address, I cannot access using 127.0.0.1). Are you sure you are modifying the correct cms.conf? The first line AWS prints is the location of cms.conf it's using.

The other thing is, you might have a firewall dropping your attempts to connect to a "weird" port like 8889 from outside.

**Comment by amisfpm** [comment]
I have run cmsAdminWebServer and open web page from other machine.
It ask loggin and password but i dont remember that have set something like that in config files.
What its default values and where i can change it?

**Comment by stefano-maggiolo** [comment]
Hi, you can use the cmsAddAdmin (in cmscontrib/) to add a new admin with a given password.
