### ISSUE TITLE
Too many not escaped html

### ISSUE THREAD

**Issue by zakuro9715** [cms-dev/cms#539]
Hi all.

I participated Japan Olympiad Informatics Open Contest. And I found many not escapted html on cms.

It means cms has many xss vulnerabilities.

Not escaped html list is following. But cms may has more else.

- User name on navbar (Loggined as ...)
- Ranking

**Comment by stefano-maggiolo** [comment]
Thanks for reporting, Takahiro. Does #538 covers all the cases you found? I cannot see any other, in particular I couldn't find any code injection in the ranking.

**Comment by stefano-maggiolo** [comment]
Given that I couldn't find more, I'm closing this, but please reopen if you find them. Thank you!
