### ISSUE TITLE
Possibility of inconsistency between FSObject and LargeObject object.

### ISSUE THREAD

**Issue by wafrelka** [cms-dev/cms#540]
Since a `FSObject` and the corresponding `LargeObject` have different granularity of database transaction, there is a possibility that a `FSObject` exists in the DB but the corresponding `LargeObject` doesn't exist in it under some conditions (example: after a CMS process was killed during file storing).
If once we fall into the problem, we cannot use `FSObject#get_lobject` and `FSObject#delete` functions (calling them causes exceptions because of invalid `loid`). We must delete the row manually using raw `loid` to fix the situation.
In this situation we cannot get, overwrite or delete the file via `FileCacher` (backed up with `DBBackend`). We cannot use `FileCacher#check_backend_integrity` function, too.

If a `FSObject` of an executable file fall into the problem during a contest, we cannot judge the submission even if we invoke the recompilation operation. Normally, the digest of an executable file doesn't change between compilations, and the recompiled executable file cannot be stored in the DB due to the problem described above. As a result, a `Worker` cannot fetch the executable file and evaluate it. There's no way to reevaluate the submission successfully via the interface of `AdminWebServer`.
This is a problem because another minor issue during a contest may lead this fatal situation.

Additionally, there is another possibility of file inconsistency due to the processing way of `FileCacher`.
The digest and the content of the file may differ under some conditions (ex: after a CMS process is stopped by Ctrl-C during file storing). In this case we cannot simply use `FileCacher#put_file_***` functions again to overwrite it because these functions do nothing when a `FSObject` with the same digest exists in the DB even if the corresponding `LargeObject` is corrupted. In order to ensure the file will be stored in the DB correctly, We must check the consistency and delete the file if necessary before calling `FileCacher#put_file_***` function.

It is not practical to check file consistency before/after every call of `FileCacher#put_file_***` and `FileCacher#get_file_***` functions.
I think atomicity of file operation must be provided at a certain layer.

**Comment by wafrelka** [comment]
The problem is that the commit of `FSObject` is done before the commit of `LargeObject` (https://github.com/cms-dev/cms/blob/master/cms/db/filecacher.py#L266).
As a consequence, these objects become inconsistent when an error occurs between the commits of `FSObject` and `LargeObject`.
The commit of `LargeObject` should be done before the commit of `FSObject`.

Plus, the rollback of `LargeObject` isn't executed even if an error occurs during file storing (https://github.com/cms-dev/cms/blob/master/cms/db/filecacher.py#L568) so that the actual content of `FSObject` may be different from its hash value.

**Comment by wafrelka** [comment]
This causes file inconsistency described #635.

**Comment by wafrelka** [comment]
Currently, CMS stores files as the following way.

1. Allocate a loid (by creating a `LargeObject`)
2. Save the loid along with the hash value of the file to store (as a `FSObject`)
3. Store the actual file content by using the loid

When something goes wrong between (2) and (3), everything corrupts.

I think that the inconsistency can be solved by simply reversing the order of operations: storing the file content first and updating the `FSObject` table later. While it may require garbage collection in case of crashes or parallel commits into the `FSObject` table, there is no possibility to have dangling `FSObject` entries.

In order to reduce `FSObject` commit conflicts, it may be good to check the `FSObject` table before storing to see whether there is an entry with the same hash.

**Comment by stefano-maggiolo** [comment]
Thanks, do you want to prepare a PR?

**Comment by bblackham** [comment]
I'm preparing one at the moment using @wafrelka suggestion.

**Comment by stefano-maggiolo** [comment]
PR was merged!
