### ISSUE TITLE
Latest documentation has instructions for Ubuntu version past EOL

### ISSUE THREAD

**Issue by myungwoo** [cms-dev/cms#550]
I've just created Amazon AWS instance and just install below packages.
It's Ubuntu 14.04 64bit server.

```
build-essential fpc postgresql postgresql-client gettext python2.7 iso-codes shared-mime-info stl-manual cgroup-lite
python-dev libpq-dev libcups2-dev libyaml-dev libffi-dev
nginx-full php5-cli php5-fpm phppgadmin texlive-latex-base a2ps
python-setuptools python-tornado python-psycopg2 \
     python-sqlalchemy python-psutil python-netifaces python-crypto \
     python-tz python-six python-beautifulsoup python-mechanize \
     python-coverage python-mock python-requests python-werkzeug \
     python-gevent python-bcrypt patool
```

But there is error 500 at /aws/contest/1/user/1.
Log tell me.

```
2016-02-23 11:31:06,157 - ERROR [Admin,0 7 base::write_error] Uncaught exception (AttributeError("'ParticipationHandler' object has no attribute 'get_query_argument'",)) while processing a request: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1141, in _when_complete
    callback()
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1162, in _execute_method
    self._when_complete(method(*self.path_args, **self.path_kwargs),
  File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 2297, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/handlers/base.py", line 164, in newfunc
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3.dev0-py2.7.egg/cms/server/admin/handlers/contestuser.py", line 150, in get
    page = int(self.get_query_argument("page", 0))
AttributeError: 'ParticipationHandler' object has no attribute 'get_query_argument'
```

It's resolved with `sudo pip install -r requirements.txt`.
What's the problem?

+) there's no documentation update in [readthedocs installation](http://cms.readthedocs.org/en/latest/Installation.html), while [github](https://github.com/cms-dev/cms/blob/master/docs/Installation.rst) is.

**Comment by stefano-maggiolo** [comment]
We require tornado 3.2, and trusty has 3.1: http://packages.ubuntu.com/search?keywords=python-tornado&searchon=names&suite=all&section=all - indeed in the documentation we give the line to install packages on 14.10, not 14.04. Given that 14.10 has reached EOL we should upgrade the instruction to 15.10 or something...

Not sure I understand the last line, do you mean that there is a mismatch between docs and github? Readthedocs might lag a little bit behind and I just made a change, but that doesn't look like what you mean.

**Comment by myungwoo** [comment]
Oh... It was a tornado version problem. Thank you for your kind reply!
Probably, Ubuntu 16.04 will appear in this April with LTS. It would be better. :)

You understood my last line correctly. Sorry for my unskilled English.

**Comment by stefano-maggiolo** [comment]
Agree on 16.04, but hopefully will release before that :)
