### ISSUE TITLE
Cannot kill services in adminwebserver

### ISSUE THREAD

**Issue by bokse** [cms-dev/cms#554]
When i clicked kill button to kill any services(e.g. proxy service, worker, etc),
refresh symbol appeared for a few seconds.
But the service is still running.

**Comment by stefano-maggiolo** [comment]
Hi, I don't have a running instance in front of me now, but have you unchecked the "autorestart"? The UI does not react very fast to the on/off status, so if you have autorestart on most probably you won't see the service off in the UI.

**Comment by bokse** [comment]
Some evidence service didn't restart:
In ResourceService, no message that indicates service was killed appeared.
Although I unchecked "autorestart" services still cannot be killed.
Uptime of service wasn't initialized to 00:00

Please check this situation.
Thanks.

**Comment by wil93** [comment]
I confirm the issue.

`git bisect` says that 4d693f7b4fec4a1a90bb7fc58f4e5803acf0314f is the commit that introduced it
