### ISSUE TITLE
Downloading tests with / in codename fails

### ISSUE THREAD

**Issue by akmohtashami** [cms-dev/cms#582]
In admin interface, downloading input/output of a test which its codename contains '/' character, fails with error "File request failed". This is because the url used to retrieve the file returns 404 error.

**Comment by myungwoo** [comment]
What did you mean input/output of a test?
Did you mean input/output of a testcase, or input/output of a user test?

It seems codename of a testcase should be satisfied the following RE ([a-zA-Z0-9_.-]+).
You may see this RE in AWS URL matching([cms/server/admin/handlers/\__init\__.py](https://github.com/cms-dev/cms/blob/master/cms/server/admin/handlers/__init__.py)).

I think it should be improved with codename validation in adding testcase or adding testcases.

**Comment by myungwoo** [comment]
How about commit myungwoo@0b6d94c?

**Comment by akmohtashami** [comment]
I meant input/output of a testcase.
Commit myungwoo@0b6d94c prevents to add testcases with invalid codename in the admin interface. But I think this must be done at a lower level since admin interface isn't the only way of adding testcases. e.g. different loaders might create tests with invalid codenames.

**Comment by stefano-maggiolo** [comment]
Maybe a better solution would be to url-encode the testcase codename in aws - I think that is sufficient to handle codenames with special chars. I will try to see if it is enough.

**Comment by akmohtashami** [comment]
I just remembered that in output only tasks output_<codename> is used for the name of submitted files. if codenames contain characters such as `/` I think it might be a problem. So the admin might have to manually rename the data using bash, etc.

**Comment by lerks** [comment]
Fixed in #738.
