### ISSUE TITLE
Testcase include in multiple subtask(group)

### ISSUE THREAD

**Issue by myungwoo** [cms-dev/cms#586]
Is there any discussion about this?

I think it is much better if single testcase is included in multiple subtask for GroupMin, GroupMul, GroupThreshold scoretypes.
It could be resolved by modifying score parameter I guess.

**Comment by stefano-maggiolo** [comment]
Yes, you can! wafrelka did some work to have regex-based group definition, so you can name your testcases (for example) .<subtask>.<subtask>.:<name> and use regexes such as 
`[^:]*.<subtask>.[^:]*:.*` (or something simpler if you assume name is not going to be "strange").

**Comment by myungwoo** [comment]
Awesome!
