### ISSUE TITLE
Unable to rename entries from cmsRankingWebServer

### ISSUE THREAD

**Issue by praveingk** [cms-dev/cms#590]
Hi,

I had created some testing contests before the actual contest. Lets say the task name is "A" for the test purpose. Now, before the actual contest, I had renamed the task name to "A_old". However, in the ranking server, its being displayed as "A".

Is there any way to sync the rankingwebserver with cmsadmin/contest?

Thanks,
Pravein.

**Comment by stefano-maggiolo** [comment]
The way to "sync" data after these kind of incompatible changes is to wipe out everything from RWS (`cmsRankingWebServer -d`) and restart cmsProxyService to reupload the data.

The only changes that the protocol support are scoring and rescoring, for all changes to the underlying data you need to wipe out and restart.

PS: this question was good for the mailing list ;)

**Comment by praveingk** [comment]
Thanks Stefano. :)
It works.

On Fri, Mar 18, 2016 at 12:24 AM, Stefano Maggiolo <notifications@github.com

**Comment by wil93** [comment]
This is probably related to #488
