### ISSUE TITLE
Some text in CWS isn't translated

### ISSUE THREAD

**Issue by wafrelka** [cms-dev/cms#591]
Some text (for example, "Execution killed with signal %d (could be triggered by violating memory limits)" message in the submission detail page) isn't translated even if corresponding text seems to exist in `cms/locale/{lang}/LC_MESSAGES/cms.po`.
I tested in Japanese, Korean, Russian, Chinese and Italian language setting but in all cases the message "Execution killed with ..." in the submission detail page isn't translated into local language.
Replacement of %d in the message seems to be performed before translation. Is it the cause?

**Comment by myungwoo** [comment]
Yeah. You are right.
There was a minor bug.
Thanks for reporting!

**Comment by wafrelka** [comment]
The bug seems to be fixed. Thank you.
