### ISSUE TITLE
IP auto login disables password auth method

### ISSUE THREAD

**Issue by akmohtashami** [cms-dev/cms#596]
By enabling IP auto logins, computers that their IP is not assigned to any user aren't able to login using normal username-password authenticate method.

One way to fix this would be to allow username-password authentication method for those users that do not have an IP assigned to them. Another would be to move authentication method to Participation so it would be either IP-based or password-based.

**Comment by karliss** [comment]
It seems that pull request was merged. Can this issue be closed?
