### ISSUE TITLE
Set time limit for comparators

### ISSUE THREAD

**Issue by wafrelka** [cms-dev/cms#626]
Generally, a comparator (in Batch task) must be written carefully so that it can judge arbitrary user's output correctly. However, sometimes there is a bug in a comparator which causes infinite loop for unexpected user's output. It will prevent all workers from processing another job, and break the entire contest.

I want to add a (optional) time limit and a memory limit for comparators (in Batch task) and managers (in Communication task) to avoid the situation (at least to make the system continue to judge submissions for other tasks). There are two ways to implement this feature, I think.
- Add `comparator_time_limit` field in `Dataset` class, or
- Provide a time limit via `task_type_parameters`

I'm wondering which one is better. What do you think?

**Comment by wil93** [comment]
Maybe it makes sense to have a "time limit for internal operations" which would used for stuff like compiling user program and running checker programs.

The easiest way to add it would probably be as a `cmsWorker` command line flag (which defaults to, say, 20 seconds) but that's just one way to do it..

**Comment by stefano-maggiolo** [comment]
Seems like a good idea!

I agree with @wil93, I don't think this should be an parameter of the task/dataset or even the contest, it can be an internal constant, if done with a sensible value and documented. If you feel strongly, you can add an override flag for cmsWorker. 

As for code location, I think you can add this as a default time limit when the task type does not provide one, so probably this can only touch Sandbox.py.

**Comment by stefano-maggiolo** [comment]
The default limit is 10s CPU-time, 21 wall-clock time. Note for the moment this applies to checkers in Batch and OutputOnly. I will refactor TwoSteps to use it too for the checkers. It doesn't apply to Communication manager.

I'm open to hear your opinions about:
- is the default reasonable for checkers?
- should the same limit be applied to Communication's manager (currently it has allocated the same time as the contestant's solution).

**Comment by wafrelka** [comment]
I think it's better to also apply the limit for Communication's managers, because the current limit is insufficient in some situations.
Currently, if a user program consumes nearly full wall-clock time but finishes within the limit, it's hard for a manager to complete the evaluation step within the limit, resulting an internal evaluation error.

**Comment by wafrelka** [comment]
The default value seems to be reasonable.

**Comment by stefano-maggiolo** [comment]
We eventually used num_processes * (time_limit + 1) (or 10 seconds if greater) see https://github.com/cms-dev/cms/pull/965/commits/f2163e01b8ab2dec2de9bcf561485a252bf60cf0#diff-751acd13b229de0916e9a9a9e04c2c1eR251 for the rationale
