### ISSUE TITLE
Ranking chart displays wrong range

### ISSUE THREAD

**Issue by ecnerwala** [cms-dev/cms#642]
The colored range on the rank chart in the contestant detail view which displays the number of users with equal score is incorrect. The number of users with equal score is often negative, which is certainly wrong. This seems exacerbated at the beginning of contests when users have score of 0.

See screenshot below.

<img width="940" alt="screenshot 2016-08-16 01 11 29" src="https://cloud.githubusercontent.com/assets/7088371/17692389/6baaff3c-634e-11e6-838f-39f9dad454ff.png">

**Comment by lerks** [comment]
See #641. For the situation you report to happen a different backend would have to be used, and that is a setup we don't support.
