### ISSUE TITLE
Free Pascal Dependency

### ISSUE THREAD

**Issue by qnighy** [cms-dev/cms#645]
I think the package `fpc` in Ubuntu (mentioned in docs) pulls unnecessary X-related dependencies.

Can we reduce that (in docs)? Although I don't know much about Pascal, the following list seems sufficient for headless environments:
- `fp-compiler`
- `fp-units-base`
- `fp-units-db`
- `fp-units-fcl`
- `fp-units-fv`
- `fp-units-math`
- `fp-units-misc`
- `fp-units-net`
- `fp-units-rtl`

Moreover, many of them seems unnecessary for competitive programming. For example, `fp-compiler`, `fp-units-base`, `fp-units-math`, `fp-units-misc`, and `fp-units-rtl` seems sufficient.

**Comment by stefano-maggiolo** [comment]
I'd like to! Let's pull in a Pascal expert, @klenin, what do you think? Which packages are needed for competitions?

**Comment by klenin** [comment]
Do you mean server or client?
For client, there is text-based IDE which may depend on `-fv` for example.
Also, customary way to program in Free Pascal is to use Lazarus IDE, which
pulls graphics anyway.
For server most of those seem indeed unnecessary.
However, there is an argument to be made for server and client configurations
to be exactly the same.
We took great efforts to insure that in Russian OI and last IOI.

So in my opinion this comes down to contest rules:
you may hold "console-only" contest with all kinds of graphics environments banned,
or you may provide online judge/problem archive without any guarantees of
similarity between client and server environments,
or finally you may hold on-site contest similar to IOI.
I would suggest that graphics-related packages should be excluded from first two,
but not the last one.

**Comment by stefano-maggiolo** [comment]
This was for the evaluation (we don't handle the environment on the clients). 

Given that as you said it boils down to contest rules, I'm happy to "suggest" only a minimal environment and admins can install more packages as they see fit.

Looking at Masaki's list, math and misc seem also unnecessary (the former is for interfacing to gmp and other math libraries, the latter for packaging and zlib). @qnighy how about keeping only `fp-compiler fp-units-base fp-units-rtl`?

**Comment by klenin** [comment]
Note that `-fcl` provides sets/maps while '-math` provides long integers.
Both are considered advantageous features in competitive programming.

**Comment by qnighy** [comment]
`fp-units-misc` seems to include a FFT library. Features like FFT, sets, maps and long integers are useful in some kind of contests.

In my opinion, while X-related dependencies are heavy, two or three packages are light. Therefore I suggest including `fp-compiler fp-units-base fp-units-fcl fp-units-misc fp-units-math fp-units-rtl`.

Also, can I ask a very basic question: are these libraries enabled by default (without explicit command-line options) ? I thought they are. If not, we just have to include libraries enabled by default.

**Comment by wil93** [comment]
FWIW: on Ubuntu 16.04 I typed "fpc", but it wasn't installed, so I got an error message saying that I should install  `fp-compiler-3.0.0` (it didn't suggest `fpc`). I installed that, and it's just a 22 MB download, and it seems to work.

**Comment by stefano-maggiolo** [comment]
Done.
