### ISSUE TITLE
Align contest data between CMS and RWS (i.e. make CMS team-aware)

### ISSUE THREAD

**Issue by lerks** [cms-dev/cms#65]
At the moment CMS doesn't support teams, because they're not needed to run the contest. RWS is the only piece of CMS that supports them, because the ranking is the only part where they make sense. 

That means that SS isn't able to send team data to RWS (even if it sends everything else) and contest administrators need to insert it manually, by creating some JSON files for the teams and editing JSON files for the users.

We may want to align the contest data that these two "instances" have, and the only way I see to achieve that is to make CMS team-aware, i.e. add a Team class to the DB model.

**Comment by stefano-maggiolo** [comment]
Fixed by wil93 PR.
