### ISSUE TITLE
When new a contest error ?

### ISSUE THREAD

**Issue by Jackyen** [cms-dev/cms#665]
sorry when I new a contest it's always print this error.
AttributeError("'Contest' object has no attribute '_col_props'",)

any one can help QQ

**Comment by stefano-maggiolo** [comment]
Hi, I think that the most plausible issue here is that you have the wrong version of sqlalchemy (probably outdated, but maybe too new?) 

Assuming you're running the version from master, we support 0.9.x and 1.0.x. If you have a different one, the easiest way to make it work is through a virtual environment, see the documentation for how to do it.

**Comment by Jackyen** [comment]
Thanks a lot.
It's sqlalchemy's problem.
Actually I read the document first ,I set the sqlalchemy version to 1.0.0
Now I'm setting the sqlalchemy version to 0.9.0.
It works.
