### ISSUE TITLE
User tests block compilation result saving

### ISSUE THREAD

**Issue by karliss** [cms-dev/cms#676]
To reproduce:
* Submit a user test in CWS
* Observe that test gets stuck in Compiling.. state , after that other submissions also get stuck
* There are no warning messages in Logging service
* Running ES manually shows a stacktrace
[error_log.txt](https://github.com/cms-dev/cms/files/614787/error_log.txt)

It seems that UserTestResult isn't created anywhere except get_result_or_create which is never called. Replacing  `object_.get_result` with  `object_.get_result_or_create` in https://github.com/cms-dev/cms/blob/691c2fe77c437b547137dd80cdce832b83683f9c/cms/service/EvaluationService.py#L596 got me a bit further, but I am not sure if UserTestResults wasn't supposed to be created earlier.  If maintainers can explain where the TestResults are supposed to be created I will create a pull request. It would be also nice to hear how `EvaluationService write_results_one_row` can write anything to DB without touching `session` variable.

**Comment by wil93** [comment]
Is this v1.2?

I remember this issue, but I think it was fixed in master

Il dom 27 nov 2016, 17:56 karliss <notifications@github.com> ha scritto:

**Comment by karliss** [comment]
I used master.

**Comment by stefano-maggiolo** [comment]
Found the problem, fixed, will submit soon (I'm trying to add functional tests for user tests too so that this doesn't happen regularly...)

**Comment by karliss** [comment]
Great, thanks for quick response.

**Comment by stefano-maggiolo** [comment]
For once... :D 

If you need it now, here's the fix: https://github.com/stefano-maggiolo/cms/commit/1b7e87bb061be19362606719eb154c3bc6485799

**Comment by stefano-maggiolo** [comment]
Submitted, with also the tests I promised, hopefully user tests will be more stable in the future. Thanks for reporting!
