### ISSUE TITLE
Occasional 404 for /tasks/{name}/submissions/{id}

### ISSUE THREAD

**Issue by karliss** [cms-dev/cms#696]
Yesterday we had a fairly big contest ~200 users and Log was spammed full with `WARNING	ContestWebServer,2 404 GET /tasks/sometask/submissions/7`. Contest was using somewhat recent version of CMS from git without language plugin related changes.  I have also seen it a few times when testing various other versions from master, but no reliable way of reproducing it yet. The best I can do is submitting large amount of solutions and actively clicking/refreshing the submission page in CWS.

Has anyone seen this problem?

**Comment by karliss** [comment]
I was able to replicate this somewhat reliably. 

* Create a  new contest and a participant.
* Disable all workers except one.
* Create a task and add a bunch tests and increase time limit so that testing takes at least minute or two.
* Create a solution which times out, infinite loop is fine.
* Submit two submissions in a row.

First submission keeps the worker busy so that second submission has to wait until it gets compiled. I guess that making a request to tasks/taskname/submissions/{id} while submission is waiting to compile results in 404. Probably caused by result not being created until compilation has started.

**Comment by wil93** [comment]
I think we should introduce a new state "Queued" which happens before
compilation. It makes a lot of sense because it's not unusual for a
submission to stay in "Compiling.." state when all workers are busy (so the
state is essentially wrong, because the submission is not even compiling,
it's just waiting).

FWIW, codeforces has the "in queue" state.

Il sab 28 gen 2017, 15:50 karliss <notifications@github.com> ha scritto:

**Comment by stefano-maggiolo** [comment]
I agree that "in queue" makes sense, but then one could be "in queue" when compiled too (waiting for evaluations)...

**Comment by karliss** [comment]
I agree with "in queue" before compilation, not so much before evaluation. Evaluation process is not a single action, it can be split across multiple workers, priorities (if they are implemented) could delay testing for some of the test cases. 

Adding new  testing states is a bit risky. Depending on how soon the 1.3 is going to be released, maybe it's better to delay such changes.

**Comment by stefano-maggiolo** [comment]
Yeah, not now. Possibly later, but I don't see it as high prio.
