### ISSUE TITLE
Language code issue

### ISSUE THREAD

**Issue by myungwoo** [cms-dev/cms#716]
Language code issue caused by e16ad23

Previous dump doesn't work in newest version.
And current dump doesn't work in old version **even if db version is same**.

(guess)
previous language code: "cpp", "java"
current language code: "C++11 / g++"

(solution)
update db version & make updater.py (is it right?)

**Comment by wil93** [comment]
Yes, and possibly an updater.sql as well, since I believe the plan is to now support SQL updates directly (yay). I was planning on doing it myself eventually, but if anyone wants to do it it's OK for me.

**Comment by myungwoo** [comment]
I don't know about supporting SQL updates directly since I didn't contribute CMS few months ago.

It would be better if you work on it. 😄

**Comment by stefano-maggiolo** [comment]
Yeah, sorry for not putting the updater in the same commit - I completely forgot about it. It should be fixed in https://github.com/cms-dev/cms/commit/233713b99dfb5877514f08bddaf320d390971a47 and https://github.com/cms-dev/cms/commit/c5c9c1ae72ab061e5f2a6728bf614245f63acb2d
