### ISSUE TITLE
Change the meaning of some variables in the --filename option of cmsExportSubmissions

### ISSUE THREAD

**Issue by wafrelka** [cms-dev/cms#730]
If we want contestants to submit their output and source code in OutputOnly tasks (like GCJ), we usually set the SubmissionFormat to something like `["output_data.txt", "source.%l"]`.

`cmsExportSubmissions` command cannot handle this configuration properly. Neither `--filename {name}{ext}` nor `--filename {name}` are expanded to the actual filename specified in the SubmissionFormat. `{name}{ext}` is expanded to `output_data.txt.c` and `source.c`. `{name}` is expanded to `output_data.txt` and `source`. This is inconvenient.

I want change the meaning of some variables in `--filename` option of the command. I want change `{ext}` to reflect the actual extension and `{name}` to reflect the actual basename so that `{name}{ext}` will be expanded to the actual filename properly.

Additionally, I want add a new variable which is expanded to the submission time in a more comfortable format like `20170324135522` (`yyyymmddhhmmss`).

What do you think about this suggestion?

**Comment by stefano-maggiolo** [comment]
The current meaning seems indeed a bit counterintuitive... Would there be a reason not to use {name} as the full name, including language extension converted from %l to the explicit one? I.e., is there a need to use basename?

If not, we could change the meaning of {name} and remove {ext}.

No problem for adding a human readable timestamp.

**Comment by wafrelka** [comment]
- Change the meaning of {name} as the full file name and remove {ext}
- Add {stime} variable representing the timestamp in the short `yyyymmddhhmmssmmm` format
- Add {task} variable representing the task name

I think these changes are reasonable. I will implement these features.

**Comment by wafrelka** [comment]
Any recommendations about the variable names?
I think {stime} and {task} are not so good.

Additionally, the current variables' names are also not so good.
For example, what does the {name} variable stand for?
The file name? The username or the task name?
I want to change the names but I have no idea what names are suitable for these variables.

**Comment by wafrelka** [comment]
fulfilled by #910
