### ISSUE TITLE
Possible bug in smartmappedcollection

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#736]
@lerks any ideas?

In the code below, `t` is an instance of Task.

SQLAlchemy version used is >1.0,<1.1 as required by CMS.

```
....
  File "/home/lversari/cmsocial/cmsocial/server/pws.py", line 1057, in task_handler
    dict([(l, s.digest) for l, s in t.statements.iteritems()])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 599, in get
    return self.set_committed_value(state, dict_, value)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 1074, in set_committed_value
    collection, user_data = self._initialize_collection(state)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 986, in _initialize_collection
    self.dispatch.init_collection(state, collection, adapter)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/events.py", line 1606, in wrap
    fn(target, value, *arg)
  File "/home/lversari/cms/cms/db/smartmappedcollection.py", line 46, in cb_on_init
    coll.on_init()
  File "/home/lversari/cms/cms/db/smartmappedcollection.py", line 146, in on_init
    assert not self.linked
AssertionError
```

**Comment by lerks** [comment]
No ideas from just looking at that.

Is it deterministic? Does it happen every time you run that code? Did you do any change that started triggering it? Did you update the micro version of SA?

I think that even though SMC does completely legal things with the SA API our use case isn't really what the devs had in mind and thus it's always a mess. I could start debugging this again, or we could get rid of SMC entirely. It was never really necessary, it was mostly to prevent some pitfalls when using SA collections (and it was a nice excuse to learn more about the internals of SA). I believe nothing would break if we were to replace SMC with a regular collection.

What's the general opinion around this?

**Comment by wil93** [comment]
> Is it deterministic? Does it happen every time you run that code? Did you do any change that started triggering it? Did you update the micro version of SA?

I will let @veluca93 reply

> I could start debugging this again, or we could get rid of SMC entirely. It was never really necessary, it was mostly to prevent some pitfalls when using SA collections (and it was a nice excuse to learn more about the internals of SA). I believe nothing would break if we were to replace SMC with a regular collection.

Yes please! 🤣

**Comment by veluca93** [comment]
> Is it deterministic? Does it happen every time you run that code?
Yes, happens every time without (or with?) fail
> Did you do any change that started triggering it? Did you update the micro version of SA?
It happens with sqlalchemy 1.0.x but not with sqlalchemy 0.9.x
> What's the general opinion around this?
I have absolutely no objections, I don't think I can count the amount of times something weird happened because of SMC.

**Comment by lerks** [comment]
One more thing: could you run the unit tests for SMC on the affected system? I expect them to pass but if they don't then this issue will probably be easier to debug...

**Comment by veluca93** [comment]
Yeah, they do pass.

**Comment by lerks** [comment]
Good to know. I will try to remove SMC and see whether any problems arise; if not I'll open a PR for that. What does @stefano-maggiolo think about this?

**Comment by stefano-maggiolo** [comment]
I'm all in favour of simplicity and using standard stuff. I'm ok in
tolerating somehow less simplicity in writing code if the upshot is
removing smc.

**Comment by lerks** [comment]
SMC removed.
