### ISSUE TITLE
Clean up Javascript code

### ISSUE THREAD

**Issue by stefano-maggiolo** [cms-dev/cms#74]
Our JS code is scattered in several files with very random names (see scripts.js and new_script.js).

**Comment by lerks** [comment]
I think the specific situation mentioned here has been addressed in 41ff834621001e8dae9abe4097f291c30d3a3f98. We still have some JS embedded in templates and, in general, the situation can be improved. But, after all, all of our code could be made more modular and improved, and I don't think JS deserves a dedicated issue for that. Closing.
