### ISSUE TITLE
Misdetection of psycopg2 version

### ISSUE THREAD

**Issue by lucach** [cms-dev/cms#750]
Oddly, on some systems `psycopg2.__version__` is shown in format `x.y` instead of `x.y.z` (e.g. `2.6 (dt dec pq3 ext lo64)`).

Consequently, [this line](https://github.com/cms-dev/cms/blob/master/cms/db/types.py#L42) raises `ValueError`:
```
    if tuple(int(x) for x in psycopg2.__version__.split('.')[:2]) >= (2, 7):
ValueError: invalid literal for int() with base 10: '6 (dt dec pq3 ext lo64)'
```

**Comment by wil93** [comment]
The correct solution is probably to use the [packaging](https://pypi.python.org/pypi/packaging) package:

```
>>> from packaging.version import Version
>>> Version("2.7.8") < Version("2.7")
False
>>> Version("2.3.8") < Version("2.7")
True
```
