### ISSUE TITLE
Same Issue with #560

### ISSUE THREAD

**Issue by myungwoo** [cms-dev/cms#771]
Hello, long time no see.

Same Issue with #560 .
It occurs again.

It seems [this part](https://github.com/cms-dev/cms/blob/6ac7eb8e90124a24b012a6794782d3a7ce244b84/cms/server/contest/handlers/contest.py#L297-L299) doesn't work well.

Right now, I've not enough time to fix it. If nobody tries this, I'll fix it later.

Thank you,

**Comment by lerks** [comment]
I tried reproducing the issue as described in #560 and hit upon a totally different error. I fixed that in https://github.com/lerks/cms/commit/7bcbf294dc8ea0ccbffaa5256e9e9d28fd75e760. Could you check whether that commit fixes your issue as well?

**Comment by myungwoo** [comment]
Okay, now it's work for me. However, cookie-based language selection doesn't work (it's totally different issue).

Do you have an idea why it doesn't work?

**Comment by lerks** [comment]
@stefano-maggiolo reported that same problem in https://github.com/cms-dev/cms/pull/761#issuecomment-302956954, yet I am not able to reproduce it.

**Comment by lerks** [comment]
Sorry, my bad, I didn't think of testing in single-contest mode. I found your bug and I think I fixed it in https://github.com/lerks/cms/commit/10e37c71f84b9ae3a9d88462eaecd6db45f2979b. Can you verify?

**Comment by myungwoo** [comment]
Okay, it seems working well.

Fixed: not choosing English when en is not in allowed_localizations
Fixed: Language switching

Thank you 👍

**Comment by myungwoo** [comment]
Why don't you add this commit to master branch?

**Comment by wil93** [comment]
https://www.youtube.com/watch?v=W-TE_Ys4iwM

**Comment by stefano-maggiolo** [comment]
Fixes for me too, merging. 

@wil93 you should listen to better music, try https://www.youtube.com/watch?v=jwv5oQPlrbw
