### ISSUE TITLE
Improve parsing of non-trivial lines in `gen/GEN`

### ISSUE THREAD

**Issue by lucach** [cms-dev/cms#779]
Consider the following `gen/GEN`:

```
# Subtask 1: Examples
#ST: 0
#COPY testo/input0.txt
#COPY testo/input1.txt
```

The first line is a comment and it's correctly ignored by `cmsMake`. The second one is correctly interpreted as "new subtask with 0 points".
The third and the fourth, **while being non-trivial** (as they do not start with `#<space>`), are silently ignored because of missing `:` after `#COPY`.

At the bare minimum we should log a warning.

**Comment by stefano-maggiolo** [comment]
PR merged.
