### ISSUE TITLE
Login fails with 'Unexpected IP' when IP address or subnet is set to 0.0.0.0

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#797]
I have installed CMS v1.3rc0 and upon starting a new contest when I tried to log in I got the following error from the cmsContestWebServer:
```
2017-09-15 12:00:14,639 - INFO [Contest,0] Unexpected IP: user=<user> pass=<pass> remote_ip=127.0.0.1.
2017-09-15 12:00:14,645 - INFO [Contest,0] 302 POST /login (127.0.0.1) 24.95ms
127.0.0.1 - - [2017-09-15 12:00:14] "POST /login HTTP/1.0" 302 326 0.029016
2017-09-15 12:00:14,689 - INFO [Contest,0] 200 GET /?login_error=true (127.0.0.1) 9.98ms
127.0.0.1 - - [2017-09-15 12:00:14] "GET /?login_error=true HTTP/1.0" 200 2677 0.014951
```
Looking in the administrative interface I saw that this user (which I imported from an existing configuration file) has assigned as "IP address or subnet" the value `0.0.0.0`. I removed that entry and I was able to login.

This is confusing because `0.0.0.0.` usually means any IP.

**Comment by stefano-maggiolo** [comment]
Hi Cristian, that's true, we don't accept 0.0.0.0 to mean "any ip". Tbh I'm not eager to implement it as a special case, it would be strange in case of autologin too. If you don't set the IP address is equivalent to what you'd expect setting it to 0.0.0.0.

If you want to send a patch to add the special case (and a new line in the help in AWS saying it's equivalent to the empty field), I'll merge it though.

**Comment by lerks** [comment]
Also, that field is supposed to be a subnet, so if you had put `0.0.0.0/0` it may have worked (not sure, though). We also accept IP addresses there but we implicitly convert them to `/32` subnets.

**Comment by stefano-maggiolo** [comment]
Well, if you use subnets you can use <anything>/0 and would have the same effect!

**Comment by CristianCantoro** [comment]
@lerks the field is named "IP address or subnet", though, so an IP address seems an acceptable value in there.

Leaving the field empty seems the most natural thing if one wishes not to put any restriction on IPs or subnets. However, I faced this problem only because when importing it was filled with `0.0.0.0` and I had that setting explicitly set in the configuration file.

I am not sure it is useful to implement the special case.
