### ISSUE TITLE
Installation produces SyntaxError

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#798]
Running `[sudo] python setup.py install` produces the following `SyntaxError:
```
/usr/lib/python2.7/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '1.3.rc0' to '1.3rc0'
  normalized_version,
  File "build/bdist.linux-x86_64/egg/cmstestsuite/code/compile-fail.py", line 1
    wibble monster
                 ^
SyntaxError: invalid syntax

zip_safe flag not set; analyzing archive contents...
cmstestsuite.Test: module references __file__
cmstestsuite.testrunner: module references __file__
cmstestsuite.RunTimeTest: module references __file__
cms.plugin: module references __file__
cms.conf: module references __file__
cms.grading.Sandbox: module references __file__
cms.service.PrintingService: module references __file__
cmscontrib.loaders.polygon: module references __file__
  File "/usr/local/lib/python2.7/dist-packages/cms-1.3rc0-py2.7.egg/cmstestsuite/code/compile-fail.py", line 1
    wibble monster
                 ^
SyntaxError: invalid syntax
```
The installation continues with seemingly no issues.

**Comment by stefano-maggiolo** [comment]
That's our test program to make sure CMS handles well Python solutions with syntax errors :D 
I have no idea know how to tell setuptools to ignore that... and I tried. It's not a problem with find_packages() - I tried creating a packages just for cmstestsuite/code and excluding it, and still showed the error. Might be a problem with package_data, but I have no idea why setuptools cares whether python files there have syntax errors...

**Comment by CristianCantoro** [comment]
You could add a custom error message saying that this error is expected and it is safe to ignore.

**Comment by wil93** [comment]
I think the issue here might be how setuptools treats package data ending in `.py`

pypa/setuptools#1177
