### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by hermanzdosilovic** [cms-dev/cms#802]
Is there a Docker image for CMS? How hard would it be to set this up in Docker?

**Comment by lerks** [comment]
We don't provide an official/supported one. We briefly discussed this some time ago and there didn't seem to be any intention on providing one soon. I think, though, that @wil93 explored it and possibly developed something, maybe he can help you out.

I'm closing this issue but if anyone has anything to add please do so and use this as a discussion forum on this matter (and have this serve as future reference). In general, though, consider asking this sort of questions on our chat first: https://gitter.im/cms-dev/cms

**Comment by wil93** [comment]
I'm planning to set up a Dockerfile at least for local development, reopening to track progress.

**Comment by wil93** [comment]
Dockerfile was added as part of #1221
