### ISSUE TITLE
How add python3 in CMS1.3

### ISSUE THREAD

**Issue by jonhte** [cms-dev/cms#803]
Hi all.

I am an user of CMS1.3 (https://cms-dev.github.io).

I have a questions:
How add Python3 in CMS1.3.

Please guide step by step.

Thanks a lot.

**Comment by stefano-maggiolo** [comment]
Hi @jonhte - I think @andreyv was working on this. Andrey, do you have something we can submit or at least share?

**Comment by andreyv** [comment]
Sorry, I didn't look further than initial evaluation.

Some notes cat be found at https://gitter.im/cms-dev/cms?at=59c76356cfeed2eb65441332.

**Comment by stefano-maggiolo** [comment]
Thanks! I can probably cook up something even if maybe not perfect.

**Comment by jonhte** [comment]
I read: https://www.freelists.org/post/contestms/Wall-clock-Python3-and-Nginx-in-CMS13

I copy file python2_cpython.py ==> python3_cpython.py, and change cmd line python2 to python3 inside python3_cpython.py.  (in folder cms/grading/languages)
**But everything not change**
