### ISSUE TITLE
how change timezone in cms1.3

### ISSUE THREAD

**Issue by jonhte** [cms-dev/cms#804]
how change timezone in cms1.3???

In Contest configuration, I see "TimeZone" place, but when I change timezone here - everything not change ???

(timezone name I found here: https://gist.github.com/ukanga/1271034)

**Comment by wil93** [comment]
Please use the [gitter chat room](http://gitter.im/cms-dev/cms) for support. It's more immediate than waiting for replies here, and in this way people won't receive too many emails 😉

**Comment by lerks** [comment]
Please read the documentation carefully:
http://cms.readthedocs.io/en/v1.3/RankingWebServer.html#logo-flags-and-faces
http://cms.readthedocs.io/en/v1.3/Configuring%20a%20contest.html#timezone

If you can't find the answers you're looking for, ask on Gitter (see @wil93's post). Use issues on GitHub only for (potential) bugs. If you end up opening an issue, keep it on a single topic, don't rename and edit it once you've found a solution and need help with another matter. That helps other people with the same problem find the solution.
