### ISSUE TITLE
New sandbox working slower than version 1.2

### ISSUE THREAD

**Issue by ashikoff** [cms-dev/cms#806]
Hello,

I've noticed something bad when I upgraded to CMS 1.3. I'm long time organizer of all Bulgarian programing contest and we are using CMS for 4 or 5years now. With old version I've tested that task with 50 tests each with time limit 1 sec takes approximately 55 seconds to grade on the worker. To my surprise it took almost double that time on 1.3 version. After analyzing this in dept I've come to a conclusion that the time to start/initialize sandbox in 1.3 is much longer than in 1.2. For example grading a task with 20 tests with 0.2 time limit each takes around 20 seconds.

My questions is - is there something I can configure to improve that, or it is thing I should work with.

Thanks in advance

**Comment by gollux** [comment]
This is probably related to https://github.com/ioi/isolate/issues/34. A newer Linux kernel should help.
