### ISSUE TITLE
"Using default port 5432 for Postgres DB" reported for Unix sockets

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#807]
The warning about the default PostgreSQL port is reported even for Unix (non-TCP/IP) connections. It comes from `cms/db/session.py`.

See http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#unix-domain-connections, the Unix socket connection is indicated by an empty host value in the connection string.

**Comment by andreyv** [comment]
A workaround to avoid the warning is to specify a dummy port: `postgresql+psycopg2://cmsuser:your_password_here@:5432/cmsdb`

**Comment by CristianCantoro** [comment]
Just a comment in passing, specifying the port - even if it is the default port - eliminates the warning also for TCP/IP connections (even local ones).
```
postgresql+psycopg2://cmsuser:your_password_here@localhost:5432/cmsdb
```
