### ISSUE TITLE
cms.conf missing - error cmsInitDB

### ISSUE THREAD

**Issue by Hacper** [cms-dev/cms#815]
Hello,
I want to install CMS 1.3. I installed. Now running. I stopped at cmsInitDB. After running this command, it gets the error:
```
2017-12-22 09:23:29,263 - WARNING [<unknown>] No configuration file found: falling back to default values.
2017-12-22 09:23:29,648 - CRITICAL [<unknown>] Operational error while talking to the DB. Is the connection string in cms.conf correct?
```
I created the cms.conf file in the config folder. I completed it with my login data to the database. What to do?
Regards.
Sorry for my English.

**Comment by wil93** [comment]
Hi, did you run the `prerequisites.py` script? Among other things it does, this script creates a copy of `cms.conf` in the correct place (`/usr/local/etc/`).

Also, github issues (even though they are called 'issues') are meant for bug reports, not for support on these issues 😄 it is better to use the official chat for this kind of questions: http://gitter.im/cms-dev/cms

**Comment by Hacper** [comment]
I don't run `prerequisites.py`. I use a first method of installation.

**Comment by Hacper** [comment]
I move to the gitter.
