### ISSUE TITLE
DumpImporter fails on 32-bit systems because timestamps are too large

### ISSUE THREAD

**Issue by lerks** [cms-dev/cms#848]
The contests we create for testing have an end date in the year 2100. When this is exported, the end date is stored as a floating-point UNIX timestamp (number of seconds since 1970-01-01 00:00:00 UTC) whose integral part doesn't fit into a 32-bit signed integer. Upon reimport the datetime library fails to parse these timestamps back into a datetime object.

I'm not sure how this can be fixed. Either we provide our own converter that works on 32-bit systems (it will be slower though). Or, for a start, we avoid using dates so far into the future. Or we declare CMS incompatible with 32-bit systems.

**Comment by stefano-maggiolo** [comment]
FWIW we don't use 2100 anymore. I think we only used it when importing a contest with --test, which I sneakily deleted recently.

**Comment by wil93** [comment]
> FWIW we don't use 2100 anymore

There are some occurrences here and there

https://github.com/cms-dev/cms/blob/a369a245f992e144072b6b60dd233086be288c83/cms/db/contest.py#L193L215

**Comment by stefano-maggiolo** [comment]
Oh you're right, my git-grep-fu was bad. I'll remove them.

**Comment by stefano-maggiolo** [comment]
Fixed
