### ISSUE TITLE
Start being more future-proof

### ISSUE THREAD

**Issue by lerks** [cms-dev/cms#86]
We could start writing some more Python 3 compatible code, to ease a transition that, sooner or later, we'll have to do. Modifications we could (should?) do include:
- Add `from __future__ import absolute_import` in all our modules. We will then see if we were doing any "implicit" relative imports (I doubt it, since we usually tried to make absolute ones... RWS could be an exception). I think we could then change many imports to be "explicitly" relative, by doing `from . import foo`.
- Add `from __future__ import division` in all our modules and start doing `a // b` instead of `a / b` when we mean integer division (also, we could start doing `a / b` instead of `float(a) / b`). It's a small but nasty detail, so I think it's better to move to it ASAP to identify bugs.
- Add `from __future__ import print_function` in all our modules. We don't use the print that often, so it shouldn't be a big issue.
- Use `io.open` instead of the builtin `open` function for file access. This allows to specify file encoding to open files as unicode strings. We started doing something similar by using `codecs.open`: this one is better, since it's the same code used in Python 3.
- In general, define better were we expect unicode text or binary data, and act accordingly. Most of the library we use already handle unicode objects (e.g. SQLAlchemy, Tornado, etc.). We could start adding `from __future__ import unicode_literals` and start looking what breaks, and fix it.
- Other things I currently don't remember.

Useful resources for Python 3 support can be found here:

http://docs.python.org/3/howto/pyporting.html
http://packages.python.org/six/
https://docs.djangoproject.com/en/dev/topics/python3/
http://techspot.zzzeek.org/2011/01/24/zzzeek-s-guide-to-python-3-porting/
http://python3porting.com/

**Comment by wil93** [comment]
Hello, I recently read about [asyncio](https://docs.python.org/3/library/asyncio.html), a module available in the standard library starting from Python 3.4. To me, it looks like this is "the future" and gevent is not needed anymore (but I could totally be wrong), so I'd like to ask (to whom is involved with the gevent use in CMS) if asyncio is a viable option and if it's reasonable to start porting CMS to Python 3.4.

**Comment by giomasce** [comment]
I do not know asyncio, but at the moment I am pretty satisfied with gevent and I do not see any real reason to switch. Switching would probably require a lot of work to test and debug again what comes out and I think that time is better spent on something else.

**Comment by lerks** [comment]
The only missing feature from the original list is `division`. It makes the most sense to just add this as we port to Python 3 instead of doing it as a separate previous step. This is being tracked in #286, hence I'm closing this one.
