### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by abdrakhman** [cms-dev/cms#871]
when running `cmsInitDB`
Error occurred 
`2018-02-27 18:26:24,564 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2018-02-27 18:26:25,279 - CRITICAL [<unknown>] Operational error while talking to the DB. Is the connection string in cms.conf correct?`
Can you help me?

**Comment by stefano-maggiolo** [comment]
Hi @abdrakhman, it means the string you set in cms.conf is not correct to access your DB (or you didn't create the DB in the first place). Make sure the host and port are the one postgres is serving from, and username, password, and db name are correct.

PS: if you need help with configuration and installation, please don't use github's issues; instead, join the gitter chat at https://gitter.im/cms-dev/cms - there more people will see this and try to help.
