### ISSUE TITLE
Python3 readiness

### ISSUE THREAD

**Issue by rcabreu** [cms-dev/cms#880]
Hello,

How can I use Python3? What do I have to do? Which version should I install?

I see commit 14f76b4ae8f959a57bd61da93b351f9b2426a6fc is called " Python3 and better support..."  from Oct. 2017, but the latest stable version, 1.3rc0, is from Mar. 2017. We have used CMS successfully for a few years now and would like to continue using it, as we believe this is a great tool (thanks for your hard work!).

**Comment by stefano-maggiolo** [comment]
Hi! 1.3 doesn't and won't support python 3, but 1.4 will support both 2 and 3 (in particular, the master branch, where the development happens, should already run correctly with python 3).

We have vague plans of dropping python 2 from 1.5, but we'll see.

If you must use python3, you can give master a shot - we try to keep it in working conditions, and if not we'd be happy to receive bugreports :)
