### ISSUE TITLE
CWS can't find localization data

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#887]
Using CMS master with Python 3 and Ubuntu 18.04, I get
```
WARNING [Contest,0] No allowed locale matches any installed one. Resorting to en.
```
when I specify the "lv" locale in the list of allowed localizations in AWS.

Localization is available at `/usr/local/lib/python3.6/dist-packages/cms-1.4.dev0-py3.6.egg/cms/locale/lv` and accessible by the CMS user. CMS Python dependencies are installed from Ubuntu repositories.

**Comment by lerks** [comment]
After a discussion on Gitter it turned out the `.po` files had not been built into `.mo` files.
