### ISSUE TITLE
Issue Request/Finding

### ISSUE THREAD

**Issue by raylin01** [cms-dev/cms#890]
Hi all,

I am trying to figure out how to use CMS so that it only awards points after the user has solved at least 1/2 of the test cases. If they did not get at least 1/2 of the test cases, then they will receive 0, but when they pass the 1/2 way point, they can get partial credit.

Also, does anyone know if the CMS ranking is by Time of Submission as a tie breaker?

Thank you!

**Comment by lerks** [comment]
I'll start by answering the second one: the ranking does not break ties, if two contestants have the same score they will be ranked ex aequo (I think that they are displayed sorted by last name).

As for the first question, I couldn't come up with any way to do that on a "vanilla" CMS. If you really want, however, you can provide your own ScoreType that can implement any custom scoring policy. Look at the files `cms/grading/ScoreType.py` and `cms/grading/scoretypes/*` to see how it is done.

**Comment by stefano-maggiolo** [comment]
Hi Ray, I don't think we have an out-of-the-box solution for your scoring needs, but it's pretty easy to build one. You need to write a new score type. The simplest way is to derive from ScoreTypeGroup, and override the reduce method to count how many correct outcomes it sees, and return 1 if more than half, 0 if less than. You can see an example to tweak here: https://github.com/cms-dev/cms/blob/master/cms/grading/scoretypes/GroupMin.py (this will give you something more general, that is you will be able to define several groups of testcases that behave like you described, but you just need to define one group and your good to go).

As for tie breaker, we don't discriminate between contestants with the same score, they will have the same rank.
