### ISSUE TITLE
Regression introduced in 5585da36294e438d955dbe6c1122a1680385d7c5 breaks cmsMake

### ISSUE THREAD

**Issue by wil93** [cms-dev/cms#897]
**Description:** cmsMake doesn't work correctly: the first testcase is consistently evaluated correctly (in my case, it gives me `Output is correct`), but all the other testcases are evaluated incorrectly (in some cases they are all `Output isn't correct`, in some other cases they are all `Execution timed out`)

**Steps to reproduce:**
1. Run cmsMake with CMS before commit 5585da36294e438d955dbe6c1122a1680385d7c5
2. Run cmsMake with CMS on commit 5585da36294e438d955dbe6c1122a1680385d7c5

**Expected:** they should both work the same

**Actual:** step 1 works, step 2 doesn't

### System Information

**CMS version:** 5585da36294e438d955dbe6c1122a1680385d7c5
**Was CMS installed:** yes
**Using a virtualenv:** yes
**Distribution and version:** Ubuntu 17.10

**Comment by stefano-maggiolo** [comment]
I can't repro this, I tried on this problem: https://github.com/olimpiadi-informatica/oii/tree/master/2017/territoriali/discesa (after setting a time and memory limit) and I get 100 and 20 on the two solutions, which is the same before and after that commit.

**Comment by stefano-maggiolo** [comment]
Discussed offline - bug manifests only in some tasks.

Debugged a bit, the triggering condition is reading from stdin/stdout. The reason it happens is that cmsMake creates the tasktype once and calls evaluate multiple times, but after the change in that commit, evaluate is not idempotent wrt the task type object itself.

I think this is a bug of the task type, it is reasonable to reuse the same instance to evaluate multiple times. I will fix it soon.
