### ISSUE TITLE
Contest Server Problem

### ISSUE THREAD

**Issue by raylin01** [cms-dev/cms#901]
Hi,

I am running into problems while running my contest server (contest is live right now). We have around 5 of each services

Here is the log: 

11:26:13 | WARNING | Worker,5 |   | Using default port 5432 for Postgres DB
-- | -- | -- | -- | --
11:26:13 | ERROR | EvaluationService,3 |   | Received error from Worker: `JobException: u'Request received, but declined because of acquired lock (Worker is busy executing another job, this should not happen: check if there are more than one ES running, or for bugs in ES.' Traceback (most recent call last): File "/home/bisvccsclub/cms/cms/io/rpc.py", line 382, in process_incoming_request response["__data"] = method(**request["__data"]) File "/home/bisvccsclub/cms/cms/service/Worker.py", line 166, in execute_job_group raise JobException(err_msg) JobException: u'Request received, but declined because of acquired lock (Worker is busy executing another job, this should not happen: check if there are more than one ES running, or for bugs in ES.' '.
11:26:13 | ERROR | EvaluationService,3 |   | Worker,1 signaled RPC for method execute_job_group was unsuccessful: JobException: u'Request received, but declined because of acquired lock (Worker is busy executing another job, this should not happen: check if there are more than one ES running, or for bugs in ES.' Traceback (most recent call last): File "/home/bisvccsclub/cms/cms/io/rpc.py", line 382, in process_incoming_request response["__data"] = method(**request["__data"]) File "/home/bisvccsclub/cms/cms/service/Worker.py", line 166, in execute_job_group raise JobException(err_msg) JobException: u'Request received, but declined because of acquired lock (Worker is busy executing another job, this should not happen: check if there are more than one ES running, or for bugs in ES.' .
11:26:13 | WARNING | Worker,1 |   | Request received, but declined because of acquired lock (Worker is busy executing another job, this should not happen: check if there are more than one ES running, or for bugs in ES.

**Comment by wil93** [comment]
Are there more than one EvaluationService running? There should be one

If you are in a contest now, join the chat for faster support! https://gitter.im/cms-dev/cms

**Comment by lerks** [comment]
This was triaged on gitter and turned out to be both a misconfiguration of services (multiple instances of services that should have one copy per contest or per machine, too many workers, ...) and, most importantly, also an occurrence of #888. I'm closing as there's nothing we need to track here.
