### ISSUE TITLE
"Outcome is not a float", even when the error is something else

### ISSUE THREAD

**Issue by Harniver** [cms-dev/cms#904]
**Description:** CMS doesn't behave properly when a checker uses too much memory or too much time or doesn't print a float number or crashes.

**Steps to reproduce:**
1. create a batch task with a checker (which requires more memory or time than the task limits)
2. try to evaluate it with cmsMake or with a Worker

**Expected:** the checker runs without being stopped (or at least CMS stops it and gives back a meaningful error). It would be reasonable to have outcomes like "Output is correct", "Time limit exceeded" and then "Internal error: checker crashed", instead of having the worker itself (or cmsMake) die.
The checker should be run with higher limits than task solutions anyway.

**Actual:** CMS stops the checker and crashes (!) complaining that the checker didn't print a float number.

### System Information

**CMS version:** master
**Was CMS installed:** yes

**Comment by stefano-maggiolo** [comment]
Hi @Harniver - my understanding is that the checker runs in an unlimited sandbox (for time and memory). Are you referring to a communication's manager?

**Comment by Harniver** [comment]
Yes, sorry, I was referring to a communication manager!

**Comment by stefano-maggiolo** [comment]
This should be fixed with the latest round of improvements to Communication. If it happens again, please open a new issue, thanks!
