### ISSUE TITLE
Documentation bug for contest limits

### ISSUE THREAD

**Issue by yihangho** [cms-dev/cms#924]
According to the [documentation][documentation], the units for `min_submission_interval` and `min_user_test_interval` are minutes:

> [...]  the minimum amount of time, in **minutes** [...]

However, it appears that the units should be in seconds. The popup tooltip in the admin panel seems to agree with this. (Ref [admin tooltip][admin-tooltip].)

[documentation]: http://cms.readthedocs.io/en/v1.3/Configuring%20a%20contest.html
[admin-tooltip]: https://github.com/cms-dev/cms/blob/223c2637d9587521198c92d3c44a1d48c3539fb5/cms/server/admin/templates/contest.html#L241

**Comment by lerks** [comment]
Thanks for the report, this has been fixed in 8b68cd5d45a9bd6a91b9d4980ccd5a1d5badc9b0.
