### ISSUE TITLE
Verbatim HTML appears in ScoringService errors

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#926]
When ScoringService fails, it may log errors such as

```
Unexpected error when executing operation `scoring submission <a href="./submission/6">6</a> on dataset 1'.
```

However, after #813 error messages are displayed verbatim in AWS, which leads to HTML code being displayed instead of actual markup.

The same error message in the log file is fine:

```
ERROR [Scoring,0 8 triggeredservice::run] Unexpected error when executing operation `scoring submission 6 on dataset 1'.
```

**Comment by karliss** [comment]
Somethink like `row.apend(link_submissions($('<td>').append($('<pre>').text(message)).html()))`
