### ISSUE TITLE
Compilation time reported only for the last compilation command

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#927]
When a language definition has multiple compilation commands, compilation time seems to be reported only for the last of them.

Steps to reproduce:
- Modify language compilation commands, for example, in `java_jdk.py`, to contain
  ```
  ["/bin/sh", "-c", "X=$(seq 1 10000000)"], ["/bin/true"]
  ```
  as the last two items. The penultimate command takes about 1 second and 158 MiB to run.
- Submit a solution using the modified language.
- CWS submission result reports compilation time about 0.005 s. Used memory seems to be correct.

Probably it is also good to check that the compilation time limit is applied to all compilation commands together and not to each of them separately.

**Comment by stefano-maggiolo** [comment]
Yup. As a matter of fact, I was in the process of cleaning up that part of `grading/` and noticed the same (and will fix, in some way).

It's hard to apply limits to all commands together (and eventually, for compilation it doesn't really matter the precise limit, for evaluation it should be the task type to decide how to proceed). But at least we should report the "sum" of the statistics.
