### ISSUE TITLE
Language list too long in AWS contest configuration

### ISSUE THREAD

**Issue by andreyv** [cms-dev/cms#930]
In the AWS contest configuration page, the "Allowed programming languages" row is becoming too long to fit on screen. See attached screenshot.
 
![screenshot-2018-4-8 admin test](https://user-images.githubusercontent.com/397308/38466183-ebaae626-3b2d-11e8-8adb-ad0b77bd61e5.png)

Listing one language per line (using `<br/>`) seems wasteful too, so I looked into allowing content wrapping in the corresponding table cell. The typical advice is to use `table-layout: fixed; width: 100%;` to achieve text wrapping in a table. However, this doesn't seem to work for me in Firefox. Furthermore, `table-layout: fixed;` results in a weird-looking first column (takes half of vertical space).

**Comment by wil93** [comment]
display: flex;
flex-wrap: wrap;

**Comment by lerks** [comment]
`<select multiple>`?

**Comment by wil93** [comment]
I didn't know select multiple (it can be tested [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple)), it's neat but you have to CTRL + click (so a help text is needed) and, most importantly, a misclick can cause you to lose the subset you selected (and at that point you have to refresh the page to restore the list)

IMO in this case the wrapping works better

**Comment by wil93** [comment]
If someone wants to open a PR, I just tested that it's enough to add these CSS rules to the parent `<td>`:

```
display: flex
flex-wrap: wrap
width: 100%
```

**Comment by stefano-maggiolo** [comment]
How about we use @wil93 suggestion and move to select multiple when we'll have a framework handling the "enough JS and CSS"?

**Comment by stefano-maggiolo** [comment]
![2018-09-14-221203_1246x446_scrot](https://user-images.githubusercontent.com/485490/45575408-557bfa80-b86b-11e8-85de-a9f1eeea67a9.png)

https://github.com/stefano-maggiolo/cms/commit/ded1e19b556d968d12dea1e215225d448184dfc0
