### ISSUE TITLE
Confusion over self.locale type in CWS's BaseHandler.

### ISSUE THREAD

**Issue by bblackham** [cms-dev/cms#98]
In CWS, Tornado expects get_user_locale() to return a tornado.locale.Locale, but in BaseHandler, it instead returns a gettext.locale, and thus Tornado is hopelessly confused.

The scenario that led to this is: In format_amount_of_time() in cms/server/**init**.py, a locale parameter is passed in, which should be a tornado.locale.Locale. However, in the one place it is used (contest/overview.html), it comes from self.locale. self.locale comes from BaseHandler.get_user_locale(), which is now of the wrong type. Therefore, the "locale.list()" call in format_amount_of_time() throws an exception.

To reproduce: set a per-user timer for the contest, and visit the front page of CWS before the contest opens. (I think that's all that's required).

**Comment by lerks** [comment]
Happens to have been fixed in #837.
