### ISSUE TITLE
Support for automatic login based on IP address

### ISSUE THREAD

**Issue by bblackham** [cms-dev/cms#99]
Here's a feature we plan to use at IOI 2013: instead of distributing usernames and passwords, we instead repurpose the IP address field to automatically log users into the contest when it begins.

The feature is implemented in the last 3 commits of https://github.com/bblackham/cms/commits/ip_autologin . An existing configuration variable in cms.conf `ip_autologin` is added.

Note that its behaviour is orthogonal to ip_lock (but uses the same IP field).
- `ip_autologin` true, `ip_lock` true: Users with an IP in the database will be autologined based on their assigned IP. Users without an IP in the database can login using username/password (assuming they are not connecting from a machine with an IP in the database already).
- `ip_autologin` true, `ip_lock` true: Users from the right IP will be autologined, but nothing prevents them logging in with a username/password from elsewhere.
- `ip_autologin` false, `ip_lock` true: No change from existing behviour.

Also worth noting is that autologin does not create a login cookie. This means that if the IP addresses in the database are changed, the changes will be reflected immediately to users.

I'm proposing this for 1.x.

**Comment by lerks** [comment]
Appears to be done in 3c2dc8043a89c2c9cebab7bd76426beee762dfbf. Closing.

(I was really talking much crap four years ago...)
